### ISSUE TITLE
Unable to run 10.5 client, even after applying Unlocker 2.0.8

### ISSUE THREAD

**Issue by fhgwright** [DrDonk/unlocker#1]
From the description, it seemed that Unlocker was supposed to allow me to run client versions of 10.5 and 10.6, in spite of VMware's position that only the server versions of those OSes can be legally run in a VM (a position not supported by the text of the actual license agreement).  In particular, I saw the following in the revision history:

02/01/15 2.0.3 - Added EFI firmware files to remove Server check

However, I was still unable to run the client version of 10.5 under Fusion 8.1.0 under OS 10.9.5 on a mid-2012 MacPro.

When I got the usual "not OS X Server" dialog box (when trying to boot from the Leopard Install DVD), I thought that maybe the patch wasn't sufficient  by itself and added _isolation.tools.osNotMacOSXServer.disable = "TRUE"_ to the .vmx file.  As usual, that suppressed the "not OS X Server" dialog box, but the boot still failed later with a different"not a server" error (that looks like it comes from EFI).  Then I thought that perhaps the Unlocker patch only fixed HDD booting and not DVD booting, so I tried an install using the Leopard Install ISO that I'd patched to look like OSX Server (for the installer OS, not the installed OS).  As usual, the install then ran to completion, but the attempt to boot the installed OSX from the HDD failed.  So AFAICT, Unlocker didn't fix anything at all.

**Comment by DrDonk** [comment]
Hi

Unfortunately the patching of the EFI firmware files was not stable and caused exceptions. So in 2.0.8 they were removed. From the readme.txt.

14/11/15 2.0.8 - Player 12 on Linux fixes
               - Get latest VMware tools command
               - Removed firmware files
               - Moved to PyInstaller 3.0

I have another method which fixes the installation image and allows client installs for 10.5 & 10.6. It isn't released yet, but if you want to try the script please let me know. You will need a functional OS X installation to the run the scripts as it involves modifying DMGs.

**Comment by fhgwright** [comment]
Ah, OK, I'd missed that.  In that case, I guess Unlocker doesn't do anything for me at all, since the only thing I need is the ability to run the client OSes.

If your DMG patcher just involves adding the ServerVersion.plist file, I already know how to do that. :-) The problem with that approach is that the file needs to be present on every boot to make Fusion happy, but if one runs with that file in place, certain things look serverish, including Software Update, which wants to update it as a server.  And trying to dynamically switch serverness during a reboot to install updates might confuse things.

If your unreleased code is in a GitHub branch, I can look at it there.
