### ISSUE TITLE
Make EFI Patcher with one click (activatable and deactivatable)

### ISSUE THREAD

**Issue by icecoffeeabell1835** [DrDonk/unlocker#11]
```
EFI Patcher

VMware will not allow the client (non-server) Leopard and Snow Leopard verions of Mac OS X to be installed due to Apple's EULA. This is implememted in the virtual EFI firmware and this can be patched to override the check if you want to use the client versions.

Please see the efi-readme file for details on patching the ROM files used by VMware products.
```

Hello,

I don't currently like this solution because is user unfriendly, this should be improved and a script should be created where can activate and deactivate EFI Patcher with one click. Additionally if `cmd` is used again, `cmd` should also show if it was successfully activated or deactivated. `cmd windows` should not be closed automatically.

**Comment by DrDonk** [comment]
It will be addressed in a future version where it is all done from one command.

**Comment by DrDonk** [comment]
There are many problem running Snow Leopard on modern CPUs via VMware which cannot be easily fixed. So this is being deprecated.
