### ISSUE TITLE
到底要怎么用啊？？？

### ISSUE THREAD

**Issue by XiaoFanJX** [DrDonk/unlocker#12]
这么一个软件找不到教程！就不能简单点？

**Comment by 743859910** [comment]
推荐你看看B站这个教程：https://www.bilibili.com/video/BV1mB4y1U7Lo

**Comment by DrDonk** [comment]
I don't speak Chinese but I see this is about how to run the unlocker. I will create some tutorials in English but I am busy with other things at the moment.

Thank you for posting the Chinese language video.
