### ISSUE TITLE
使用右键菜单PS运行，可是会报错无法打开此安装程序包

### ISSUE THREAD

**Issue by kevon2019** [DrDonk/unlocker#13]
使用右键菜单PS运行，可是会报错无法打开此安装程序包

**Comment by kevon2019** [comment]
> 使用右键菜单PS运行，可是会报错无法打开此安装程序包

但是我手动定位到安装包目录，双击运行是没得问题的，不报错的

**Comment by kevon2019** [comment]
求解决办法，麻烦发到

[removed personal email address for security]

**Comment by kevon2019** [comment]
貌似知道原因了，是文件定位目录下，文件名不同，根本找不到ps文件指向msi包

**Comment by 743859910** [comment]
推荐你看看B站这个教程：https://www.bilibili.com/video/BV1mB4y1U7Lo

**Comment by DrDonk** [comment]
I don't speak Chinese but I see this is about how to run the unlocker. I will create some tutorials in English but I am busy with other things at the moment.

Thank you for posting the Chinese language video.

**Comment by 743859910** [comment]
> I don't speak Chinese but I see this is about how to run the unlocker. I will create some tutorials in English but I am busy with other things at the moment.
> 
> Thank you for posting the Chinese language video.

嗯 不用客气 大家都是在互帮互助
Well, you're welcome, everyone is helping each other

**Comment by gadgetgourmet** [comment]
It's flagged by Windows Defender as having a virus!!!!!!

**Comment by 743859910** [comment]
> 它被Windows Defender标记为有病毒！

In my opinion, choose GitHub and authors, or don't use it.

**Comment by 743859910** [comment]
Trust GitHub and author

**Comment by DrDonk** [comment]
> It's flagged by Windows Defender as having a virus!!!!!!

Where did you download it from? If in doubt build it yourself. And which version?

**Comment by gadgetgourmet** [comment]
> > It's flagged by Windows Defender as having a virus!!!!!!
> 
> Where did you download it from? If in doubt build it yourself. And which version?

I downloaded from the Github repo:  https://github.com/DrDonk/unlocker/releases
version 4.1.3

This is what Windows 11 tells me:

![image](https://user-images.githubusercontent.com/8428121/165811913-89520b03-ca7e-4686-bdd5-4f63a44d7e60.png)

**Comment by DrDonk** [comment]
Looks like a false positive on the file. VirusTotal has 6/64 detecting something with the zip file. 

https://www.virustotal.com/gui/file/47e642bcfa0733fc94e20287b034f6655169160e16c522c367e6cce5d69f3e8c/summary

**Comment by DrDonk** [comment]
I did some research and it seems certain scanners do not like executables compiled in Go. I copied a VMware distributed Go exe, vcsim.exe from gvmomi, and it also is flagged up as having a virus. Not sure there is much I can do. If in doubt get the source code and compile a version from the repo.

**Comment by DrDonk** [comment]
https://go.dev/doc/faq#virus
