### ISSUE TITLE
Unable to create a new virtual machine

### ISSUE THREAD

**Issue by yeti-code** [DrDonk/unlocker#15]
Full Error:

Unable to create a new virtual machine: Cannot open configuration file "C:\Users\****\Documents\Virtual Machines\macOS \macOS 10.15.vmx": The system cannot find the path specified.

My System:
VMWare Workstation 16 Player
Windows 11

**Comment by yeti-code** [comment]
@DrDonk I was using the latest release and ran the cmd file as specified from the README. It was in C:/ as admin. I will test again, and let you know. Thanks for the quick reply.

**Comment by yeti-code** [comment]
@DrDonk Did a fresh install of vmware same error for the win-install.cmd being run for the patch.

**Comment by DrDonk** [comment]
No updates in 14 days so closing this issue.
