### ISSUE TITLE
Unlocker413.zip is flag as a virus.

### ISSUE THREAD

**Issue by khonore** [DrDonk/unlocker#16]
See image
<img width="905" alt="unlocker413" src="https://user-images.githubusercontent.com/17768807/167333291-fdd0fe3a-fec3-47fd-a4e9-602aa7f1b59a.PNG">
s

**Comment by DrDonk** [comment]
False positive https://github.com/DrDonk/unlocker/blob/main/TROUBLESHOOTING.md
