### ISSUE TITLE
flagged as virus in malware bytes, avira etc

### ISSUE THREAD

**Issue by zakhai** [DrDonk/unlocker#17]
Title says it all.

**Comment by LordVeovis** [comment]
but you can specify the virus name in malware bytes, avira etc...

**Comment by DrDonk** [comment]
False positive.

**Comment by DrDonk** [comment]
https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg
