### ISSUE TITLE
NOT SUPPORT WINDOWS 7

### ISSUE THREAD

**Issue by Rosabis** [DrDonk/unlocker#17]
When I use your tool to unlock vmware 15.5 on windows 7,it says missing api-ms-win-core-path-l1-1-0.dll,but that's only exist on windows 8 or higher,I hope you can fix this issue.

**Comment by DrDonk** [comment]
Unfortunately Python 3.9 is only supported on currently supported Windows releases and that means 8.1 and 10. I would suggest using Paolo's C++ based unlocker.

https://github.com/paolo-projects/auto-unlocker
