### ISSUE TITLE
Vram problem

### ISSUE THREAD

**Issue by darkthepro1990** [DrDonk/unlocker#18]
Upgraded my WMware to 15 pro from 14 pro. Then I just upgraded my mac workstation from 14 to 15 and change macos version from high sierra to mojave version but after all vram is only 3 mb and I cant change it. I must use workstation 14 for more Vram ? I can build on workstation 14 but workstation 15 offer more vram than 14.

**Comment by LordVeovis** [comment]
Can you try modify this parameter directly on the vmx file ?

**Comment by DrDonk** [comment]
This is not a problem with the unlocker as it does not patch anything relating to VRAM. Suggest you raise the issue at the https://www.insanelymac.com/forum/104-multi-booting-and-virtualisation/ forum.
