### ISSUE TITLE
OS X running only in 1024x768...

### ISSUE THREAD

**Issue by GreatGranPa** [DrDonk/unlocker#19]
everything else works great 🥇

**Comment by GreatGranPa** [comment]
VMware: newest, guest OS both Catalina and big sur

**Comment by Dirk-** [comment]
Did you install the VMware tools?

Also, try to set the display settings of the VM in VMware Player.

**Comment by DrDonk** [comment]
Install the VMWare Tools as Dirk mentioned and you should be able to select other video modes. If you have already installed them and still does not change resolution you can try this. Open Terminal and run:

`sudo /Library/Application Support/VMware Tools/vmware-resolutionSet <width> <height>`

where width and height are the pixel size you want. For example to get 1440x900:

`sudo /Library/Application Support/VMware Tools/vmware-resolutionSet 1440 900`

**Comment by GreatGranPa** [comment]
will try thank you!


Viele Grüße,
Ulrich

**Comment by DrDonk** [comment]
Has this fixed the issue?

**Comment by DrDonk** [comment]
Going to add this to the troubleshooting doc and close this issue.
