### ISSUE TITLE
OSX slow after installing VMware tools

### ISSUE THREAD

**Issue by pp111** [DrDonk/unlocker#19]
I used the unlocker to install OSX in VMware 16 and all worked fine. The speed of the VM was good, however after installing the VMware tools the system was really laggy. The VMware tools were downloaded and installed automatically as expected.

I removed the VMware tools display driver (/System/Library/Extensions/VMwareGfx.kext) and the speed is good again and there are no lags (although the mouse moves slower).

Is this normal?

The problem is that without the VMware tools display driver the screen size is really small and can not be resized.

I tested it with OSX 10.14 (Mojave) and 12 (Monterey) with the same exact behavior.

**Comment by Li-Yanzhi** [comment]
Same here, I have found this issue for almost 1 year when VMWare 16 Tech Preview & Release out.  VMWare 16 is the first release that can run on Hyper-V,  so I can run VMWare VMs (e.g. MacOS) & Hyper-V VMs at same time.   I have tried on 3+ PCs for this issue, even with the latest Intel i9-12900K with 96GB RAM, the result it same: when VMWare Tools installed, then MacOS will be very laggy, and event Host machine will freeze 1-2 seconds frequently.

**Comment by pp111** [comment]
I tested it also with VMWare 15 and it has the same issue. It seems to be related to the VMWare tools and not the the VMWare version. Maybe an old VMWare tools version might work fine, but I don't know.

I can live without the VMWare tools except for the screen resolution. Did you find any way of increasing the display size without the VMWare tools? Mine is fixed to 1024x768 and can not be changed although I configure VMWare display settings to a larger resolution.

**Comment by Li-Yanzhi** [comment]
> I tested it also with VMWare 15 and it has the same issue. It seems to be related to the VMWare tools and not the the VMWare version. Maybe an old VMWare tools version might work fine, but I don't know.
> 
> I can live without the VMWare tools except for the screen resolution. Did you find any way of increasing the display size without the VMWare tools? Mine is fixed to 1024x768 and can not be changed although I configure VMWare display settings to a larger resolution.

Yes,  1024*768 is the biggest issue for this high-resolution screen era. I didn't find the way to change it :(

Did you install Hyper-V on your PC?

**Comment by DrDonk** [comment]
Can someone download and test earlier versions of the tools? I can then update the tools in the release. Currently, I am not in a position to do these tests.

https://customerconnect.vmware.com/downloads/info/slug/datacenter_cloud_infrastructure/vmware_tools/11_x

_These URLs require a VMware login to download._

**Comment by pp111** [comment]
I installed the version 11.0.0 and it is still very slow and laggy and host machine freezes frequently. Uninstalled it and VM speed goes back to normal. I also tried version 10.3.10 and it has the same issue.

I have Hyper-V enabled on my computer.

**Comment by Li-Yanzhi** [comment]
In theory, Hyper-V and VMware can co-exist and VMware will use nested virtualization on Hypervisor and performance is supposed to be acceptable (https://blogs.vmware.com/workstation/2020/05/vmware-workstation-now-supports-hyper-v-mode.html),  the current issue is VMware Tools installation on MacOS guest will dramatically slow down the guest OS performance.

I remembered that I have test this issue on a Hyper-V disabled host before and got same result. I will test it again tomorrow and report result here.

**Comment by DrDonk** [comment]
OK that’s good. Basically you are running VMware as a VM in Hyper-V as all of Windows is running as a VM on Hyper-V.
