### ISSUE TITLE
Unlocker doesn't work with Vmware 15

### ISSUE THREAD

**Issue by XandrMaster** [DrDonk/unlocker#19]
Hi Dave !
Thank you for Unlocker.
I found an issue with Vmware 15.0.0 + macOs . Host is Ubuntu 18.04.1 LTS.
![screenshot from 2018-10-06 17-28-27](https://user-images.githubusercontent.com/5524628/46572978-5f3edc80-c997-11e8-9ef8-b614b9fdf528.png)
So Unlocker doesn't work with Vmware 15
But with Vmware 14.1.3 + macOs + darwinPre15.iso everything ok .
Thanks.

**Comment by DrDonk** [comment]
It has been tested on Mint 19 but not Ubuntu. Can you list the contents of the backup folder created by the installer and attach the output of the dumpsmc.py utility, please?

**Comment by XandrMaster** [comment]
Attatched ...
[Ubuntu18_dumpsmc.txt](https://github.com/DrDonk/unlocker/files/2453254/Ubuntu18_dumpsmc.txt)

![screenshot from 2018-10-06 20-24-34](https://user-images.githubusercontent.com/5524628/46574187-8356e980-c9a8-11e8-88a3-cde1f62c906b.png)

**Comment by DrDonk** [comment]
And can you attach the VMX file please? Just checking some things. Finally what version of macOS e.g. 10.13.6

Looks like I will have to setup a test system as I cannot see anything wrong from the dumpsmc command.

**Comment by XandrMaster** [comment]
Sure , there is the my [vmx](https://drive.google.com/file/d/10lo9IJMEKCl7VF52eE4GxXFBqfvDUC0g/view?usp=sharing)  . 
Just request permissions for download.
But FYI: this is v14.1.3 vmware . I uninstalled v15 vmware.

**Comment by insaneshadowzaman** [comment]
I have tried vmware v14.1.3 + macOS 10.12 + darwin.iso (no pre15), and it worked well for me. 
And then I uninstalled v14.1.3 and installed v15.0.0. Then created a VM (macOS 10.12) and installed darwin.iso (not pre15 again). Everything went well without any errors.
Host: Manjaro linux. 
![screenshot of working macOS 10.12 in vmware v15.0.0](https://user-images.githubusercontent.com/22135181/46588506-8395d880-cabf-11e8-80d6-813f7b69d8f0.png)

**Comment by XandrMaster** [comment]
Hmm, perhaps it is issue only with Ubuntu 18 . By the way , thanks guys @DrDonk @insaneshadowzaman . I'll just stay with v14.1.3 for a while.

**Comment by DrDonk** [comment]
I tried again with Mint 19 with a Mojave guest installation from scratch and was OK. I guess will have to download Ubuntu and see if I can replicate the issue.

**Comment by survivor303** [comment]
The same problem occur on win10 with vmware 15, no mac os option :/

**Comment by DrDonk** [comment]
Please raise this as another Issue. I have it wporking on Windows 10 and no problems.

**Comment by DrDonk** [comment]
> I tried again with Mint 19 with a Mojave guest installation from scratch and was OK. I guess will have to download Ubuntu and see if I can replicate the issue.

So I have setup Ubuntu 18.04.1, Workstation 15 and a Mojave guest and it all works for me. I am not sure what to do next. Any chance that you could try again and capture the Linux unlocker output for me please?

**Comment by CDAGaming** [comment]
Just installed MacOS 10.13 (High Sierra), both clean Unlocker from this Repo, and a Newly Installed Version of VMWare Workstation 15.

So far, I haven't noticed any issues (In fact, it seems to be working much better then the previous unlocker I was using several months ago)

OS: Windows 10 19H1 Build 18252 (Insider - Fast Ring) on x64 / amd64 Architecture

**Comment by DrDonk** [comment]
> The same problem occur on win10 with vmware 15, no mac os option :/

Have you got anti-virus software running? It can interfere with patching and should be disabled when runnning the unlocker installer and uninstaller.

**Comment by ararog** [comment]
For me I'm having a permission issue while patching vmwarebase.dll even running as administrator and with anti virus turned off.

**Comment by DrDonk** [comment]
Can you capture the output of the unlocker please?

**Comment by DrDonk** [comment]
Is that all the output? There should be more from win-install.cmd.

**Comment by ararog** [comment]
@DrDonk nevermind, I've been running wrong executable. Everything is ok.

**Comment by snehil5** [comment]
> @DrDonk nevermind, I've been running wrong executable. Everything is ok.

how did you fix this?
