### ISSUE TITLE
GPU Passthru of graphics using Unlocker 2.0.7 or Unlocker 2.0.8 El Capitan ok Sierra not

### ISSUE THREAD

**Issue by c4pt00** [DrDonk/unlocker#2]
```
           Hello I have been using unlocker now for months and months with El Capitan running as a guest on my ESXI 6.0.0 host. When I run my El Capitan guest on ESXI I am able to use my passed through graphics card no problem. When I boot the guest with El Capitan the guest starts to boot and I can see the Apple in black and white loading with a white progress bar after a moment the graphics load on my monitor that is connected to my card that is passed through (With El Capitan I can use either a Radeon 6450 or a Radeon 6570)
```

I am trying to run macOS Sierra using either unlocker 2.0.7 or unlocker 2.0.8 I also have tried to upgrade from ESXI 6.0.0 to ESXI 6.0.0 update 2 (and reapplied the patch for both 2.0.7 and 2.0.8) but my graphics never arrive using the same two graphics cards (The graphics load only in the ESXI console but the graphics never arrive on my monitor that is passed through to the guest) I thought maybe that my cards were removed and no longer supported on macOS Sierra but I checked the Info.plist and I am pretty sure that my device and vendor ids are there)

Is there something missing in order to passthrough graphics to a macOS Sierra guest
because using El Capitan as a guest my graphics card worked great

**Comment by DrDonk** [comment]
This an ESXi issue and nothing to do with the unlocker. There are many threads on forums on how to do this, but it is not easy and requires certain graphics cards.
