### ISSUE TITLE
Shell extension exe prevents patching on Windows.  PR Sent

### ISSUE THREAD

**Issue by boostchicken** [DrDonk/unlocker#2]

**Comment by DrDonk** [comment]
Thanks for the PR. As you can probably guess this was my first use of Go to write something and I knew it was sub-optimal. I just wanted to get the unlocker rebuilt using something else that was easy to use in a cross platform way. I did have my original C++ lying around but have wanted an excuse to get into Go.

Would you like me to recognise you in the copyright? Happy to do so but would need your real name which you may not be wanting to do.

**Comment by DrDonk** [comment]
I've added your GitHub id to the change log. Hope that's OK for you.
