### ISSUE TITLE
Windows Defender reports that dumpsmc.exe has Trojan:Win32/Zpevdo.A

### ISSUE THREAD

**Issue by oogba71** [DrDonk/unlocker#20]
Screenshot of proof attached.

![image](https://user-images.githubusercontent.com/11686668/46579393-8d93da80-c9de-11e8-80c9-5416ae7b8f31.png)

**Comment by oogba71** [comment]
I *think* this might be a false positive since Malwarebytes says it's clean.

**Comment by DrDonk** [comment]
It is a false postive due to using PyInstaller. Some AV find the bootstrap program as a virus/trojan.

**Comment by DrDonk** [comment]
I am looking to see if I can find another way to package the Python code for Windows. If you are not sure you can install Python and I can change the bqatch script to use the Python script instead.

**Comment by oogba71** [comment]
Looks like you fixed it. Windows Defender says the whole distribution is clean and Kaspersky says dumpscn.exe is clean. Thanks!
![image](https://user-images.githubusercontent.com/11686668/46620529-fb312b00-caf2-11e8-98f1-e77c4e077d48.png)
