### ISSUE TITLE
Windows folder missing?

### ISSUE THREAD

**Issue by FrancWest** [DrDonk/unlocker#21]
Looks like the Windows folder with the .exe's is missing from the download?

![Snag_aa6a5ba](https://user-images.githubusercontent.com/16062624/172181188-fa50c7e0-3206-4e99-8d3d-2d2db6ce52fd.png)
?

**Comment by DrDonk** [comment]
That's the source code download which GitHub generates when creating a release. You need this https://github.com/DrDonk/unlocker/releases/download/v4.2.1/unlocker421.zip
