### ISSUE TITLE
ESXi 6.7?

### ISSUE THREAD

**Issue by tostaky10** [DrDonk/unlocker#21]
Thanks so much for this invaluable tool! Forgive me for being dumb but I don't see the script for ESXi in this latest release? ESXi is referenced in your notes but I don't see anything to run on the host. Any help greatly appreciated! Thank you!

**Comment by Ash258** [comment]
https://github.com/DrDonk/esxi-unlocker

**Comment by tostaky10** [comment]
Amazing - thanks so much for the quick response! Apologies for being an idiot!
