### ISSUE TITLE
Unsupported NAT Driver in macOS 13

### ISSUE THREAD

**Issue by MacTaylor-beta** [DrDonk/unlocker#22]
Seems that the newest network driver is unavailable in macOS 13 Beta 1.

Unlocker Version 421
VMware Workstation 16.2.3 build-19376536
macOS 13 Developer Beta 1 Build 22A5266r

**Comment by DrDonk** [comment]
This is a VMware issue and not unlocker related. Please read this VMware forum post.

https://communities.vmware.com/t5/VMware-Fusion-Discussions/macOS-13-Ventura-VM-Intel/m-p/2913104
