### ISSUE TITLE
Cannot change resolution on Vmware 15

### ISSUE THREAD

**Issue by chenyisen** [DrDonk/unlocker#23]
Hi DrDonk,
Thanks for your contribution. I've installed 10.13(17A365) on Vmware 15, and installed darwin.iso. Everything looks well but I cann't change resolution on Macos. I wonder whether it's a mass issue.

**Comment by diassynthesis** [comment]
Facing the same issue (with 10.13 on VMware 14) and the following links helped me:
[https://www.insanelymac.com/forum/topic/315765-cant-change-display-resolution-in-macos-sierra-on-vmware/](url)

[https://www.virtuallyghetto.com/2015/10/heads-up-workaround-for-changing-mac-os-x-vm-display-resolution-in-vsphere-fusion.html](url)
