### ISSUE TITLE
error showing VMWare out-of-date

### ISSUE THREAD

**Issue by Noct-Cp** [DrDonk/unlocker#27]
![image](https://user-images.githubusercontent.com/67223445/173711781-9ff52d47-5297-481d-a601-a0dd4e6a6c4b.png)
Chinese version：
![image](https://user-images.githubusercontent.com/67223445/173711792-8fc8c982-87e9-465f-a9a9-7e358b3cb019.png)

**Comment by Noct-Cp** [comment]
My solution is to uninstall VMWare and install the older version.Any other solutions?

**Comment by Noct-Cp** [comment]
Funny thing：after I install the older version and update back into the latest version,no error occurs

**Comment by DrDonk** [comment]
I'm not sure this is an unlocker problem or a messed up VMware update. Can you give more details of what you did before the error message.

**Comment by Noct-Cp** [comment]
> I'm not sure this is an unlocker problem or a messed up VMware update. Can you give more details of what you did before the error message.

Before unlocking,it was OK.
I had used python unlocker before , so I uninstall it and used this version to unlock(using Powershell)
And this error occurs.
And I saw on CSDN that someone has met this problem before.
![image](https://user-images.githubusercontent.com/67223445/174199247-86e85129-f3a6-4a1f-bea3-5af7fe6e514c.png)

**Comment by DrDonk** [comment]
OK looks like the python uninstall and go version creates the problem. I will try. and recreate it. Thanks

**Comment by DrDonk** [comment]
I cannot re-create this.

**Comment by Noct-Cp** [comment]
> I cannot re-create this.

OK……As long as reinstalling VMWare isn't that difficult……Thanks.Now I'm using unlocker with no errors.
