### ISSUE TITLE
cannot change mac address on mac os vm's

### ISSUE THREAD

**Issue by queglay** [DrDonk/unlocker#27]
On macos vmware instances (10.13 and 10.14 tested), in the vmware network settings it isn't possible to change the mac adress because it is greyed out.

other normal linux and windows vm's are able to have their mac address changed.

**Comment by DrDonk** [comment]
I guess that is a limitation of the GUI when using macOS. It's not something the unlocker can fix. You can manually edit the MAC address in the VMX file.

**Comment by queglay** [comment]
Somehow, I unlocked this part of the ui, but I'm not sure how.  some combination of using NAT on a new virtual network, and cloning the image resulted in it working.  Hopefully its reproducible, but I will stick to editing the VMX in the future.  Thankyou for all your work.
