### ISSUE TITLE
The unlocker won't launch

### ISSUE THREAD

**Issue by MrBananaxx** [DrDonk/unlocker#28]
When i try to open the win-install.cmd as admin, the cmd close itself instantly.
Edit: I've tried with both vmware 14 & 15 and that's not working, i can't see the option.

**Comment by DrDonk** [comment]
You need to open s command prompt with admin rights and then run the installer. You should see the messages. Also 3.0.2 stops the terminal froim closing.

**Comment by MrBananaxx** [comment]
I've launched win-install.cmd as admin but that's not working, the same thing happened like previously.

**Comment by MrBananaxx** [comment]
![Screenshot](https://user-images.githubusercontent.com/44337057/47268565-f046b380-d552-11e8-9059-cf47d6b8ad32.png)

**Comment by MrBananaxx** [comment]
![Screnshot](https://user-images.githubusercontent.com/44337057/47268612-503d5a00-d553-11e8-95cd-e5988c4b4004.png)

**Comment by MrBananaxx** [comment]
![sans titre](https://user-images.githubusercontent.com/44337057/47268649-aa3e1f80-d553-11e8-85b5-a6ac2ac698b8.png)

**Comment by DrDonk** [comment]
I have never seen that. Can you edit the batch file and set echo to on please? Also it looks like you are running a localized version of Windows. Can you tell me what language it is please?

**Comment by MrBananaxx** [comment]
The language is french. And with echo on, that does the same thing.

**Comment by DrDonk** [comment]
I am out of ideas just at the moment. It seems to stop in two different places. Can you comment out the chcp 850 command and try again? Also can you open the registry editor and find the path HKLM\SOFTWARE\Wow6432Node\VMware, Inc.\VMware Player and the InstallPath key?

**Comment by MrBananaxx** [comment]
So for the InstallPath key yes i've found it, the path is : C:\Program Files (x86)\VMware\VMware Player\x64\ and C:\Program Files (x86)\VMware\VMware Player\ .
For the chcp 850 it appears only when echo is set to off

**Comment by DrDonk** [comment]
Well I am still not sure what is going on. One other idea can you get the PATHEXT environment variable for me?

**Comment by DrDonk** [comment]
Nope nothing wrong there. Can you run chop.exe in the command prompt?

**Comment by DrDonk** [comment]
Chip.exe

**Comment by DrDonk** [comment]
chcp.exe

**Comment by DrDonk** [comment]
chcp.com

**Comment by MrBananaxx** [comment]
![capture3](https://user-images.githubusercontent.com/44337057/47271908-10d83300-d57e-11e8-8efa-15f321e0000d.PNG)

**Comment by DrDonk** [comment]
OK I admit I really do not know what to do next. I could change the locale on my test system and see if it makes a difference.

**Comment by MrBananaxx** [comment]
Is it because of the blank space after delims= ? 
![captu1re](https://user-images.githubusercontent.com/44337057/47272452-484add80-d586-11e8-9850-a71dfaa4a8a2.PNG)

**Comment by DrDonk** [comment]
No that should be three as commented in the code. It should be tab character not spaces so may be worth checking as an editor could change it.

**Comment by DrDonk** [comment]
I will test this out in the morning UK time.

**Comment by MrBananaxx** [comment]
Okay i'm gonna try on another pc

**Comment by MrBananaxx** [comment]
So i've tried on another pc and that is working so i think i fucked up something in my pc. Maybe that's because i've tweaked the windows services ?

**Comment by MrBananaxx** [comment]
Everything is working now, i just reset my services to default :)

**Comment by MrBananaxx** [comment]
Everything is working now, i just reset my services to default. Thanks for your help :)

**Comment by DrDonk** [comment]
Ah interesting. I wonder what it was, but pleased it's working for you.
