### ISSUE TITLE
win-install.cmd fails

### ISSUE THREAD

**Issue by aaruni96** [DrDonk/unlocker#3]
Win-install.cmd fails (Windows 10), with the error of some exe file missing. I think 

> Windows has a packaged version of the Python script using PyInstaller, and so does not
require Python to be installed.

is no longer valid

**Comment by aaruni96** [comment]
The script works by changing "unlocker.exe" and "gettools.exe" to "python unlocker.py" and "python gettools.py" respectively, installing python2.7 (Python 3.5 errors out with syntax issues), and adding the python install directory to the CMD path.

**Comment by DrDonk** [comment]
Can you give me the exact error message please? It works for me on Windows 10.

**Comment by DrDonk** [comment]
Also did you download from the official forum topic? This is just avsource code repo for me.

http://www.insanelymac.com/forum/topic/303311-workstation-1112-player-712-fusion-78-and-esxi-6-mac-os-x-unlocker-2/

**Comment by aaruni96** [comment]
It must be this. I downloaded from this github repository, couldn't find the download elsewhere when I tried.

**Comment by DrDonk** [comment]
When you click download here you get a snapshot of the source code not the release.
