### ISSUE TITLE
How to run in linux?

### ISSUE THREAD

**Issue by jbrepogmailcom** [DrDonk/unlocker#30]
`sudo ./check.go` is not working

**Comment by DrDonk** [comment]
1. Download the latest release https://github.com/DrDonk/unlocker/releases/download/v4.2.1/unlocker421.zip
2. Unzip the archive
3. Open a terminal
4. CD to the linux folder from extracted archive
5. Run `sudo unlock` or `sudo check` or `sudo relock`

**Comment by SimPilotAdamT** [comment]
You can also do the following (this will compile from the latest source):
1. install go as well as ZSH (this varies depending on your distro)
2. `go install github.com/tc-hib/go-winres@latest`
3. `export PATH="$PATH:$HOME/go/bin"`
4. `git clone https://github.com/DrDonk/unlocker.git`
5. `cd unlocker`
6. `zsh build.sh`
7. `cd dist/linux`
8. run the binaries as needed

**Comment by DrDonk** [comment]
I should change the build scripts shebang so don't need to install zsh. I build and test on real Macs and zsh is now the default shell.

I will add proper build instructions as well. Ok to copy your Linux ones?

**Comment by SimPilotAdamT** [comment]
> I will add proper build instructions as well. Ok to copy your Linux ones?

Of course, go ahead lol. Just let me know when that is done so I can update the PKGBUILDs in the AUR

**Comment by DrDonk** [comment]
I've checked in the shell script changes to main. Still working on a build document.

**Comment by DrDonk** [comment]
OK I've added your notes for Linux. I also tidied some things up such as remove the PDFs as pandoc was being a total pain with the markdown.

**Comment by DrDonk** [comment]
Updated readme.
