### ISSUE TITLE
Error 13

### ISSUE THREAD

**Issue by Hughy123** [DrDonk/unlocker#31]
Running unlocker on win 10 pro and VMW Player 15 returns IO Error 13, permission denied for vmwarebase.dll..
Changing permissions manually for the .dll file no change.
Could Controlled Folder Access be causing this Problem? 
#19 

C:\unlocker-master>unlocker.exe
File: C:\Program Files (x86)\VMware\VMware Player\x64\vmware-vmx.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xab2f50
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xab2f70
+LKS Key:
002 0xab2fb8 +LKS 01 flag 0x90 0x140167bd0L 07
OSK0 Key Before:
241 0xab72f0 OSK0 32 ch8* 0x80 0x140167bd0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
241 0xab72f0 OSK0 32 ch8* 0x80 0x140167bd0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xab7338 OSK1 32 ch8* 0x80 0x140167bd0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
242 0xab7338 OSK1 32 ch8* 0x80 0x140167bd0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xab7380
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xab73a0
+LKS Key:
004 0xab7478 +LKS 01 flag 0x90 0x140167bd0L 01
OSK0 Key Before:
435 0xabedb0 OSK0 32 ch8* 0x90 0x140167bd0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
435 0xabedb0 OSK0 32 ch8* 0x90 0x140167bd0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xabedf8 OSK1 32 ch8* 0x90 0x140167bd0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
436 0xabedf8 OSK1 32 ch8* 0x90 0x140167bd0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

File: C:\Program Files (x86)\VMware\VMware Player\x64\vmware-vmx-debug.exe

appleSMCTableV0 (smc.version = "0")
appleSMCTableV0 Address      : 0xcbbc60
appleSMCTableV0 Private Key #: 0xF2/242
appleSMCTableV0 Public Key  #: 0xF0/240
appleSMCTableV0 Table        : 0xcbbc80
+LKS Key:
002 0xcbbcc8 +LKS 01 flag 0x90 0x14019f4c0L 07
OSK0 Key Before:
241 0xcc0000 OSK0 32 ch8* 0x80 0x14019f4c0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
241 0xcc0000 OSK0 32 ch8* 0x80 0x14019f4c0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
242 0xcc0048 OSK1 32 ch8* 0x80 0x14019f4c0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
242 0xcc0048 OSK1 32 ch8* 0x80 0x14019f4c0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

appleSMCTableV1 (smc.version = "1")
appleSMCTableV1 Address      : 0xcc0090
appleSMCTableV1 Private Key #: 0x01B4/436
appleSMCTableV1 Public Key  #: 0x01B0/432
appleSMCTableV1 Table        : 0xcc00b0
+LKS Key:
004 0xcc0188 +LKS 01 flag 0x90 0x14019f4c0L 01
OSK0 Key Before:
435 0xcc7ac0 OSK0 32 ch8* 0x90 0x14019f4c0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK0 Key After:
435 0xcc7ac0 OSK0 32 ch8* 0x90 0x14019f4c0L 6F 75 72 68 61 72 64 77 6F 72 6B 62 79 74 68 65 73 65 77 6F 72 64 73 67 75 61 72 64 65 64 70 6C
OSK1 Key Before:
436 0xcc7b08 OSK1 32 ch8* 0x90 0x14019f4c0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63
OSK1 Key After:
436 0xcc7b08 OSK1 32 ch8* 0x90 0x14019f4c0L 65 61 73 65 64 6F 6E 74 73 74 65 61 6C 28 63 29 41 70 70 6C 65 43 6F 6D 70 75 74 65 72 49 6E 63

GOS Patching: C:\Program Files (x86)\VMware\VMware Player\vmwarebase.dll
Traceback (most recent call last):
  File "unlocker.py", line 399, in <module>
    main()
  File "unlocker.py", line 395, in main
    patchbase(vmwarebase)
  File "unlocker.py", line 301, in patchbase
    f = open(name, 'r+b')
IOError: [Errno 13] Permission denied: u'C:\\Program Files (x86)\\VMware\\VMware Player\\vmwarebase.dll'
[9412] Failed to execute script unlocker

C:\unlocker-master>

**Comment by DrDonk** [comment]
You don't run unlocker.exe but win-install.cmd. It deals with ensuring system is ready to patch. It is documented in the readme.txt.

**Comment by DrDonk** [comment]
No follow up so closing.
