### ISSUE TITLE
plz provide the Unlocker of esxi?

### ISSUE THREAD

**Issue by lucaskamp** [DrDonk/unlocker#34]
DrDonk: 
              I've been looking for it for a long time, but no one updated it.  can you provide it for ESXi 7.0.3U ++ ?

**Comment by DrDonk** [comment]
I had feedback from VMware professionals that the mechanism may interfere with ESXi in certain circumstances. I have not found what causes the issue and until I do I will not be creating a new unlocker for ESXi. 

It is too risky especially if someone was to use it in a production environment.

**Comment by DrDonk** [comment]
I should point out the actual patches were OK it was the creation of a new VMTAR file which acts as an overlay to the file system which may have been the problem.

**Comment by lucaskamp** [comment]
thx DrDonk for my question. but i noticed a website called sysin.org , try to incorporate the modified patch into the esxi system firmware.  I'm not sure if this is correct, especially after you reply to me.  xD

**Comment by DrDonk** [comment]
I have been looking for another way to inject the patches, so it may happen at some point. I do know that the patches work on a test system, but the issues reported to me were from people I've known for many years and so I don't want to take any risks.

I understand that many people want it for a simple ESXi standalone server but I've heard of it being deployed in vCenter enterprise settings and I don't want that responsibility.

I did initially mark as "won't fix" but I will mark the issue as "enhancement" as the issue may get solved.

**Comment by DrDonk** [comment]
There is one other thing Go executables do not run on ESXi, so will have to be a reworked Python version, or a different language C/C++/Rust/Zig which do work on ESXi.

**Comment by lucaskamp** [comment]
I've given up, thanks a lot .  xD

**Comment by DrDonk** [comment]
I have had an idea on how to package a Python version for ESXi. I will be testing it soon, but I am currently recovering from Covid so please be patient.

**Comment by lucaskamp** [comment]
There is a website called sysin, which claims to provide ISO for writing ESXi-Unlocker, I'm not sure if there are other problems. So I will continue to wait for your news and Wishing you a healthy : )

**Comment by DrDonk** [comment]
I will be looking at this in the next couple of days. The work will be in the esxi-unlocker repo so I can keep Python based and Go based unlockers separate.

https://github.com/DrDonk/esxi-unlocker

**Comment by lucaskamp** [comment]
cool

**Comment by lucaskamp** [comment]
thx DrDonk !!!!!!!

**Comment by DrDonk** [comment]
Initial version 4 release on the other repo. Closing this issue and new comments should be posted to https://github.com/DrDonk/esxi-unlocker.

**Comment by lucaskamp** [comment]
yes thx,i test it until recently and some problem to crash
https://github.com/DrDonk/esxi-unlocker/issues/7#issuecomment-1208839525
