### ISSUE TITLE
Running Monterey successfully BUT cannot connect Ipad or Android

### ISSUE THREAD

**Issue by halinasplace** [DrDonk/unlocker#35]
I've successfully started to run Monterey Mac OS and Android Studio/XCODE flutter development with simulators but cannot for the life of me get physical devices to attach to the Virtual machine to run and test the apps ... where should I start looking ?
i might add that i used a vmware unlocker 3.03 previously and at least android was working but in attempts to get the ipad working android has stopped too for android studio no longer recognizes it ? thanks for any help and pointing me in the direction of any further information you might need to help me debug the problem ! Its a machine running windows 10.

**Comment by halinasplace** [comment]
Anyone ??

**Comment by DrDonk** [comment]
This is not an unlocker problem so you would be best asking somewhere like InsanelyMac forums.
