### ISSUE TITLE
vmware workstaton pro 16.2.3 macOS Ventura beta and it's stuck in a reboot loop !

### ISSUE THREAD

**Issue by ybrc** [DrDonk/unlocker#37]
[vmware.log](https://github.com/DrDonk/unlocker/files/9161173/vmware.log)
[Please attach as a file and not paste into the issue. Thanks.]

**Comment by DrDonk** [comment]
This is not something the unlocker can fix. Please check this out https://github.com/DrDonk/unlocker/issues/22#issuecomment-1152192394.

If that does not help it would require something from VMware.

**Comment by DrDonk** [comment]
I have just read this https://communities.vmware.com/t5/VMware-Fusion-Discussions/macOS-13-Ventura-VM-Intel/m-p/2918070#M179012.

Potentially this means that Ventura will never be useable on anything other than macOS and Fusion. It look like the Apple Paravirtualized GPU is required and that is only available on a macOS host.

**Comment by DrDonk** [comment]
@ybrc Can you attach the vmware.log and the VMX file to this issue please

**Comment by DrDonk** [comment]
Nothing in the log shows the error, and I suspect it is something VMware have to fix as also seems to be problems with Fusion on Apple hardware.

There is a new VMware tech preview dropping sometime soon. I will have another look at Ventura once that is available.

**Comment by DrDonk** [comment]
VMware have released a new 22H2 Tech preview of Workstation. Can you try that with v4.2.2 of the unlocker please?

**Comment by ybrc** [comment]
> VMware have released a new 22H2 Tech preview of Workstation. Can you try that with v4.2.2 of the unlocker please?

VMware® Workstation Technology Preview 22H2 Pro e.x.p build-20200310
Unlockerv4.2.2
Tested on macOS Monterey and everything is fine. Next, I decided to test macOS Ventura. Is there anything else I need to provide?

**Comment by DrDonk** [comment]
Did the TP not work with Ventura?

**Comment by ghost** [comment]
If Ventura requires Apple Paravirtualized GPU, maybe we build an emulator with GPU acceleration? I know it's hard, it's just in my dream, because I once discovered chinese iOS emulator called Heilei that support GPU acceleration

**Comment by DrDonk** [comment]
The is nowhere to create a hook in Workstation for AppleGPU and the settings are missing from the code. The code also requires System Libraries from Apple and I cannot see anyway to emulate that.

It would be nice to have accelerated graphics but to be honest it is a bit hit and miss that it works in macOS guests running in Fusion.

**Comment by DrDonk** [comment]
OK I completely missed the reason I think your VM does not work. It's the virtual network adapter which need to be vmxnet3 and not e1000e, not the AppleGPU.

Attached is a modified VMX file I created from the vmware.log file. Try that by copying to the VM folder.
[macOS 13.vmx.txt](https://github.com/DrDonk/unlocker/files/9260564/macOS.13.vmx.txt)

(You will need to remove the .txt off the end and make sure it's called "macOS 13.vmx")

**Comment by DrDonk** [comment]
No updates so closing!
