### ISSUE TITLE
cant find unlocker.exe and gettools

### ISSUE THREAD

**Issue by skybai1987** [DrDonk/unlocker#4]
i download zip,when i had unzip.cant find unlocker.exe and gettools.exe.

**Comment by DrDonk** [comment]
Where did you download it from?

**Comment by skybai1987** [comment]
@DrDonk your github page DrDonk/unlocker. thanks

**Comment by DrDonk** [comment]
That is just the source code, the actual release files are here:
http://www.insanelymac.com/forum/topic/303311-workstation-1112-player-712-fusion-78-and-esxi-6-mac-os-x-unlocker-2/

**Comment by skybai1987** [comment]
@DrDonk Thanks...
