### ISSUE TITLE
macOS Guests Deprecated in Fusion 13

### ISSUE THREAD

**Issue by DrDonk** [DrDonk/unlocker#40]
VMware will stop supporting new macOS versions as guests starting with Fusion 13 and the next version of ESXi.

This is documented at the VMware KB for Fusion:
https://kb.vmware.com/s/article/88697

And for ESXi:
https://kb.vmware.com/s/article/88698

This will likely impact Workstation Pro/Player as well. Currently the exact details of what make change are not clear, but it is safe to say we should look for alternative approaches to the unlocker.

**Comment by SimPilotAdamT** [comment]
Apparently it's possible to run MacOS on VirtualBox as well as via Qemu on KVM and even on Microsoft's Hyper-V... Maybe it's finally time to start switching to either of those three to prepare for this... Maybe it would be possible to modify Unlocker to bring compatibility back when the changes do happen? Granted it would take an especially long time without updating Workstation Pro/Player while the changes are made, and it would increase the size of the codebase but I think it could be done.

**Comment by DrDonk** [comment]
I have a working VMware macOS template using OpenCore that I am testing. It wouldn't need any patches, but would still use the VMware guest settings but supply the SMC data directly. 

There is a some evidence from VMware Fusion product manager that he's trying to get this overturned for Fusion on Intel Macs. Apple Silicon require a different approach using Apple supplied VM API and virtual Mac models.

The interesting thing is that they are not dropping support for currently released macOS versions.

Time will tell what's going on.

I don't have anything but Intel Macs now, and will be migrating to Apple M2 kit when the machines I need become available. So my involvement may drop, but I can test the patches using nested virtualization.

**Comment by SimPilotAdamT** [comment]
Sounds good to me... We'll see what happens when Apple drops support for X86 silicon altogether, since VMware can't just emulate aarch64.

**Comment by DrDonk** [comment]
VMware will support Intel for awhile, and they have aarch64 in tech preview. Bottom line is that VirtualBox, VMware, Hyper-V use virtualization not emulation so Intel on Apple Silicon will need QEMU or something similar.

**Comment by DrDonk** [comment]
There are issues with Venture see this issue:

https://github.com/DrDonk/unlocker/issues/47#issue-1440512657

**Comment by DrDonk** [comment]
VMware Fusion manual lists macOS 13 as supported so I think we're good for now.
