### ISSUE TITLE
Unlocker

### ISSUE THREAD

**Issue by ExcellentSpirit** [DrDonk/unlocker#41]
When you double click either check, relock or unlock, it displays yes or no for admin privilege, then, shows the command prompt and ask you to press enter, after pressing enter, the prompt disappears and it doesn't unlock, check or relock the VMWare workstation. May you resolve this please. I attempted this on Windows 11 on the latest VMWare Workstation 16 Pro. Thank you.

**Comment by DrDonk** [comment]
Did you press yes for admin privileges? I have never seen it do this before and cannot think what is causing it.

**Comment by ExcellentSpirit** [comment]
Yes, you have to press yes before the command line will open and ask you to press the enter key. When you do that, it disappears without relocking, unlocking it.

>  
> P.S. Rabbi Adlerstein reechoed ingratitude in 2 Timothy 3:2 that would be rife in the last days among other vices when he said, "we don't do well with gift!" I have and will always watch my gratitude of the gift of people and things in my life!

**Comment by DrDonk** [comment]
Do you see the banner text? I am really struggling to see what has happened here as there is unfortunately nothing on which to base any diagnostic actions.
```
Unlocker 4.2.3 for VMware Workstation/Player
============================================
© 2014-2022 David Parsons
```

**Comment by SimPilotAdamT** [comment]
I think this might actually be working as intended. The binaries were made to work in CLI, so they might actually be running when you double click and give it root access. Many DE's open a terminal window to show the command output, but not all of them do. use `htop`, `btop`, `top` or smth to see if any is still running. If they are, they're just hanging on the end but where it asks you to `press enter to continue` (which really exits the program).

**Comment by SimPilotAdamT** [comment]
I think this might actually be working as intended. The binaries were made to work in CLI, so they might actually be running when you double click and give it admin access. Most of the time PowerShell/`cmd.exe` is opened to show the command output, but not all the time. Use Task Manager or smth to see if any is still running. If they are, they're just hanging on the end but where it asks you to `press enter to continue` (which really exits the program).

edits: originally wrote this from the viewpoint of Linux, forgot that this was available for Windows too lol

**Comment by DrDonk** [comment]
BTW you can stop the last message waiting using an env variable UNLOCK_QUIET=1

I was asked to wait so that the output could be seen.

**Comment by SimPilotAdamT** [comment]
Oh nice that will be useful for my PKGBUILDs in the AUR. I'll add that in and send you those checksums when I get home.

**Comment by SimPilotAdamT** [comment]
@ExcellentSpirit how is it working for you now?

**Comment by DrDonk** [comment]
I wonder if this is related to https://forums.macrumors.com/threads/monterand-probably-the-start-of-an-ongoing-saga.2320479/page-4?post=31125212#post-31125212

**Comment by DrDonk** [comment]
No response so closing.
