### ISSUE TITLE
About This Mac

### ISSUE THREAD

**Issue by gonzabrusco** [DrDonk/unlocker#44]
This is not an issue. It's a request for help/documentation.

Is there a way of having a correct mac Serial Number and Hardware in "About this Mac" ?

Thanks
Gonzalo

**Comment by SimPilotAdamT** [comment]
Yep, if you edit the VMX file manually you can customize the virtual Mac's serial number and simulated model.

Here's what I added to my VMX file:
```bash
smbios.reflectHost = "TRUE"
hw.model = "MacBookPro14,3"
board-id = "Mac-551B86E5744E2388"
smc.version = "0"
mks.gl.allowBlacklistedDrivers = "TRUE"
```

You can look up codes to use for the `hw.model` on Apple's web page. `board-id` is for the actual serial number.

`mks.gl.allowBlacklistedDrivers = "TRUE"` is for [VMware's not-so-great Linux support](https://communities.vmware.com/t5/VMware-Workstation-Pro/Solution-for-Hardware-graphics-acceleration-and-No-3D-support/td-p/508060).

**Comment by SimPilotAdamT** [comment]
These are the latest Intel MacBook Pro models, which run 8th/10th Gen Intel Core i5's.

![Screenshot_20221005_193659](https://user-images.githubusercontent.com/71192298/194136746-d8eee305-54ca-43d3-97c5-23883ed95c8b.png)

[Source.](https://support.apple.com/en-gb/HT201300)

**Comment by DrDonk** [comment]
Here's a complete list of things you can override. I used to have this documented on Insanleymac but left there sevaeral years ago. Obviously best get your own values here but this is an example. 

I haven't tried any of this in sometime so not sure how well it all works now.

Attached a PDF of old web page with details.
[oldblog.pdf](https://github.com/DrDonk/unlocker/files/9718261/oldblog.pdf)


```
board-id.reflectHost = "FALSE"
board-id = "MAC-F22589C8"
hw.model.reflectHost = "FALSE"
hw.model = "MacBookPro6,2"
serialNumber.reflectHost = "FALSE"
serialNumber = "RM129481AGW"
smbios.reflectHost = “FALSE"
efi.nvram.var.ROM.reflectHost = "FALSE"
efi.nvram.var.MLB.reflectHost = "FALSE"
efi.nvram.var.ROM = "123456"
efi.nvram.var.MLB = "DONKDONKDONKDONKA"
```

**Comment by SimPilotAdamT** [comment]
> I used to have this documented on Insanleymac but left there sevaeral years ago.

I thought your name sounded familiar. Used to see your stuff on there all the time

**Comment by DrDonk** [comment]
Yep that was me for about 10 years providing unlockers and helping out. 

I see SimPilot in your name do you do anythong with flight sims? Back end of 90s/early 00s I wrote utilities for the aircraft MDL files in MSFS. Things like MDLRepair which was used to fix broken MDL files.

**Comment by SimPilotAdamT** [comment]
That is correct. I've been doing stuff since about 2012 when FSX was first released to Steam... I may very well have used something by you if you did make something for FSX Boxed. Right now I'm sitting comfortably on MSFS's 2020 release, having spent ~£5000 on all the hardware and software I've ever used for flight sim.

**Comment by gonzabrusco** [comment]
Thanks for the info! I will close this issue for now!
