### ISSUE TITLE
Keep rebooting on macOS Ventur

### ISSUE THREAD

**Issue by remy727** [DrDonk/unlocker#45]
I upgraded to **macOS Ventura** recently. After upgrading, I applied patches to VMware.
But I am getting this error.
![Screenshot_1](https://user-images.githubusercontent.com/69775411/199455792-1d95dca3-f4d1-4e2f-bad3-26de9d2e922d.png)

- Release version: `4.2.3`
- OS: `Windows 10`
- VMware version: `16.2.4 build-20089737`

**Comment by DrDonk** [comment]
It's a known problem with no fix currently.

**Comment by DrDonk** [comment]
Can you attach your VMX file and the vmware.log file to the issue, please?

**Comment by nathanaelytj** [comment]
Having same issue this is my VMX and vmware.log (tho some of the path and hostname info is redacted for privacy reasons)


[vmware.zip](https://github.com/DrDonk/unlocker/files/9942532/vmware.zip)

**Comment by nathanaelytj** [comment]
Here is the VMX and LOG files. Some path is redacted from log file.

[vmware.zip](https://github.com/DrDonk/unlocker/files/9942549/vmware.zip)

**Comment by DrDonk** [comment]
I took a look but there is nothing obvious in the files, but I did not know that you were running on an AMD processor. It may well be Ventura has additonal sepecific requirements on the Intel CPUs it supports causing the boot loop. I think we are going to have to wait and see what the Hackintosh community come up with for Ryzen and AMD. It may then be possible to addd more CPUID changes, but at this stage there are no guarantees.

**Comment by jeroencoolen** [comment]
Replace ethernet0.virtualDev = "e1000e" with ethernet0.virtualDev = "vmxnet3" in vmx file. Boots perfectly.

**Comment by DrDonk** [comment]
It is already set to vmxnet3 so is something else.

**Comment by DrDonk** [comment]
I've added this page to explain how to capture debug output. https://github.com/DrDonk/unlocker/wiki/Debugging-macOS-Guests

You may want to try it and post the output.

**Comment by AdrianEddy** [comment]
I have the same issue, fresh installation of Ventura, here's the serial log: 
[Ventura vmware workstation log.zip](https://github.com/DrDonk/unlocker/files/9961584/Ventura.vmware.workstation.log.zip)

**Comment by DrDonk** [comment]
@AdrianEddy Thanks for that could you run it again but leave the smcdebug=0xff parameter off the boot flags, please? I'm trying to distinguish between an SMC error or the library not being found. 

`  Reason: tried: '/usr/lib/libSystem.B.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libSystem.B.dylib' (no such file), '/usr/lib/libSystem.B.dylib' (no such file, no dyld cache)`

Also is this a vanilla macOS installer, built from macOS download?

**Comment by AdrianEddy** [comment]
[log.zip](https://github.com/DrDonk/unlocker/files/9962838/log.zip)
Yes, it's a fresh vanilla installation via bootable iso created from official macOS Ventura installer, downloaded on another mac from App Store and created using `Install macOS Ventura.app/Contents/Resources/createinstallmedia`. Installer ran successfully and installation went as expected. Installer rebooted a few times but then got stuck in the boot loop. 
Exactly the same happened after updating Monterey to Ventura via standard system update from previously working Monterey on VMware Workstation

**Comment by DrDonk** [comment]
Great thanks for helping out. I may need a bit of time to look through it. I assume Monterey ran fine on this host machine.

**Comment by AdrianEddy** [comment]
Yes, no issues with Monterey. Feel free to ask for any other logs or debugging, I'll be happy to help

**Comment by DrDonk** [comment]
@AdrianEddy Can we continue this https://github.com/DrDonk/unlocker/issues/33?notification_referrer_id=NT_kwDOAA1FpLEzODg4MTQ4MjY3Ojg2OTc5Ng&notifications_query=is%3Aunread#issuecomment-1307475635

Looks like same panic for multiple users.

**Comment by DrDonk** [comment]
Actually I have separated this into new issue:

https://github.com/DrDonk/unlocker/issues/47#issue-1440512657

**Comment by EmilAlipiev** [comment]
@DrDonk sorry asking you here. you replied me on the other thread "Create a Monterey VM attach the Ventura VM and copy data across." 
what do you exactly mean by that? I  have created a Monterey VM but I cannot acces to Ventura VM, it gives me the error messages as on this issue. So is it not recoverable and i cannot get the data from the VM?

**Comment by Mr-Smu** [comment]
This helped me with Ventura on ESXi. Add to *.vmx file or via advanced settings.

hw.model.reflectHost = "FALSE"
hw.model = "MacMini8,1"
serialNumber.reflectHost = "FALSE"
serialNumber = "000000000000"

Tested on NUC10i5 and MacMini7,1 with ESX 7U3g.
