### ISSUE TITLE
Aborting uninstall as backup folder does not exist! - VMware version: 17966106

### ISSUE THREAD

**Issue by MisiekDP** [DrDonk/unlocker#46]
Hey,
I cant install Unlocker on VMware Workstation version: 17966106.
![vmware_2022-11-07_19-56-55](https://user-images.githubusercontent.com/22171619/200392151-a291e230-51e1-44b2-abfa-a33b928e1f21.png)

Check.exe:
![check_2022-11-07_19-59-05](https://user-images.githubusercontent.com/22171619/200393658-ad67e3e2-aa74-4322-b7d0-8dd25c6d7946.png)

Relock.exe:
![relock_2022-11-07_19-59-37](https://user-images.githubusercontent.com/22171619/200393627-895c9467-8721-463a-a0b3-9304a95fc611.png)

Files tree:
![windirstat_2022-11-07_20-05-25](https://user-images.githubusercontent.com/22171619/200393620-e069441e-6c9c-4d89-8dee-a98de75e811b.png)

**Comment by SimPilotAdamT** [comment]
So I'm assuming you were able to get it working?

**Comment by MisiekDP** [comment]
Yes, I used wrong exe file :p
