### ISSUE TITLE
Cannot erase disk for MacOs on VMWare in Windows 10

### ISSUE THREAD

**Issue by etiennebon** [DrDonk/unlocker#49]
Hello,

I try to install MacOS big Sur on my VMWare player on Windows 10.
I have followed lot of different tutorials that are all the same, actually. This worked one time (the first time), but then when I deleted my VM and tried to create it again, the erase action systematically failed:
> VMware Player unrecoverable error: (aioCompletion) // Exception 0xc0000005 (access violation) has occurred.

I have full admin access on my laptop, so I guess there is some kind of "history" that is kept and that prevent me from using my disk again and erase it.

Would you have any idea how to fix that, please?

I tried:
> Running everything as admin (unlocker and VMWare)
> removing both unlocker and VMWare
> Rebooting after having installed VMWare and Unlocker
etc...

But still the same error.

Thank you.

Steve.

**Comment by DrDonk** [comment]
Have you got Anti-virus software running? This error has been reported on VMware forums and is often caused by AV software detecting false positives.

**Comment by etiennebon** [comment]
Hello, 
Thank you for your quick feedback, Dave.
I checked and I don't have any AV running on my Laptop, except Windows Defender.
I tried stopping Windows Defender totally, but no chance going forward.

I'm not able to understand what aioCompletion is used for...
I am full admin of my laptop.

Any other idea on this?

Regards,
Steve.

**Comment by DrDonk** [comment]
I suggest that you uninstall unlocker and VMware and then run some diagnostics on your drives. Just trying to rule out the obvious. 

Also check the Windows event logs for signs of errors.

When you re-install VMware try and get the installation log usually in folder pointed to by %TEMP%. Maybe there's an error in there.

**Comment by DrDonk** [comment]
Sorry I hit the close button by mistake.

**Comment by etiennebon** [comment]
Hello Dave,

I did a disk clean-up from Windows: C > Priorities > tools > Check => And no error was found (Windows has scanned the file system and found no problems).
I run the cmd: chkdsk c: /f /r /x (as administrator) and the system took several hours to fix the disk (I have only one disk on which Windows is installed, so I had to reboot my system). 

Then I re-installed both VMWare player and win-install (ad admin) => but still the same error.

FYI: I have 130Gb left on my laptop. I want to create a 100Gb disk.
When I try to shrink the disk, the  system shows me that I can create a 1.8 Gb. Which is strange, right after a disk clean-up and deep diagnostic/fix.

As I ran it a first time successfully, some weeks ago (the very first time), but never again since then, I feel like I have some kind of historic stored somewhere or some piece of my partitions corrupted, but I'm not able to figure out where.

If ou want to have a screen sharing session, please let me know. I'm based on the west coast and am an early bird.

Thanks.
Steve.

**Comment by etiennebon** [comment]
Hello David,

actually, I figured out that when I uninstalled VMWare, I kept the "VMWare config" on my laptop which is a default behavior => Unchecking this box solved the issue.
The disk space is fully released and re-usable.

I'm installing my VM right now.

Thank you for this follow-up.

Regards,
Steve.

**Comment by etiennebon** [comment]
You can close that case, now!

**Comment by DrDonk** [comment]
That's great news. Sorry didn't get back to you earlier I have a bad cold and brain was a bit fried!
