### ISSUE TITLE
Compatibility update to macOS 11.4?

### ISSUE THREAD

**Issue by Yuri010** [DrDonk/unlocker#5]
Hello!

So I accidentally installed the macOS update to version 11.4
I thought it wasn't that big of a problem until it stopped booting.
I immediately realized why: the VM version was still on 11.1.

"You should change it!".. Yeah... you would say but thats not possible as the option for Mac OS 11.4 doesn't exist yet...

This is not really to make you stress or something that it isn't working.. but more like "Hasn't VMware created the actual functionality in VMware Fusion" or didn't you guys (the maintainers of this repo) update it yet..

Im just a bit stressed and kinda want to know how long it would take until I can use my VM again

Thanks!
Yuri

**Comment by DrDonk** [comment]
VMware need to fix code. There is a thread on the VMware Fusion discussions `https://communities.vmware.com/t5/VMware-Fusion-Discussions/macOS-Monterey-VM-Black-screen/m-p/2851456#M174365 `

**Comment by DrDonk** [comment]
Sorry I misread the question and just realised it’s for 11.4 not 12. There is nothing much in the unlocked which could affected by 11.4. What issues are you seeing?

**Comment by Yuri010** [comment]
My VMware just doesn't have the option for macOS 11.4
So I guess the unlocker tool doesn't add that in VMware yet

So it still says its a 11.1 VM, while its a 11.4 guest, when I try to boot, it runs the full animation and at the end of the bar it resets and reboots... And that just repeats forever..

**Comment by DrDonk** [comment]
Not having that option should not really affect the VM and that’s something VMware add but is normally hidden except in Fusion. Can I check the following:

1. Host OS?
2. VMware product and version?
3. Can you attach the VMware.log file please?

Make sure you attach it and don”t copy it into the issue as it makes it easier for me to check.

The earliest I can take a look will now be tomorrow UK time.

**Comment by Yuri010** [comment]
Host OS: Windows 10 Pro 21H1 (64bit)
CPU: Intel Core I5 2520M
GPU: Intel HD Graphics 3000
RAM: 8GB (6GB assigned to VM)

VMware: VMware Workstation 16 Pro (most recent update)
Guest OS: macOS 11.4
Unlocker version used: 3.0.4

Ill send the VMware log tommorow

Btw: I've updated my macOS before and forgot to change from 11.0 to 11.1 and it didn't boot so I guess that option does really make a difference.

**Comment by DrDonk** [comment]
I wrote the original unlocker and that has been forked many times as I was not able to work on it for the last 4 years. Due to the large number of forks I am not sure what has been done in other forks and I no longer visit forums as it became too much like work. I spent 10 years on Insanelymac answering questions but neede to have a break. Plus I started my own company which meant I had no time to dedicate to the code.

I am doing this for fun now and actually no longer have any real need as all my computers are real Macs.

**Comment by DrDonk** [comment]
I have tested macOS 11.4 on the same version of Windows and Workstation 6.1.2 patched with 3.0.4 and it all works for me. Are there any errors in the VMware.log?

![Screenshot 2021-06-14 at 11 53 53](https://user-images.githubusercontent.com/869796/121900702-9acffe00-cd1d-11eb-8c65-0979624aad38.png)

**Comment by Yuri010** [comment]
I guess I could try reinstalling the unlocker or just reinstalling VMware in general...
Ill have to take a look in the log but I don't know when I can do that

**Comment by Yuri010** [comment]
VMware log: [vmware.log](https://github.com/DrDonk/unlocker/files/6653514/vmware.log)
It was stuck for like 45 minutes on the same screen and it was doing nothing on the disks, nothing on the cpu, just nothing. The disks in my storage server even went to idle mode so... I guess that just isn't working

I tried booting into the recovery and that succeeded but yeah.. that isn't really helping because I can't do much there

**Comment by Yuri010** [comment]
I guess I can try reinstalling from the recovery.
I don't have any data that can't be redownloaded on there anyway so..

Im just gonna wait for your answer :|

**Comment by DrDonk** [comment]
Have you applied any updates to VMWare Workstation such as 16.1.1 to 16.1.2? If so you need to re-run the unlocker as the updates overwrite the patches.

**Comment by Yuri010** [comment]
Well its not a long time ago since I did a clean Windows install and since then I didn't get any updates so.. And I retried the unlocker but it simply just doesn't add an option for 11.4, 11.1 is the maximum.

**Comment by Yuri010** [comment]
The 2nd underlined only goes to macOS 11.1 and not 11.4 and that is just the problem ![menu.jpg](https://user-images.githubusercontent.com/75804846/122062882-18643e80-cdf0-11eb-8f8e-521a5f9de772.jpg)

**Comment by Yuri010** [comment]
ehm... I don't know how... but it boots again..
I changed the macOS version from 11.1 back to 11.0 (because your VM was named like that)
but it just booted right into macOS
_"I wonder how"
"I wonder why"_

So I guess I can close the issue here..
Only problem I am still facing is that my macOS VMDK is 70GB while the guest OS says like 30GB used..

**Comment by DrDonk** [comment]
Fusion does not have the 11.1 option so maybe it's not properly implemented in Workstation.

Anyway pleased you are up and running again.

Here's a Bash script to shrink disk space:

```
#!/usr/bin/env bash
dd if=/dev/zero of=zerofile bs=16m count=1000000
sync
rm zerofile
/Library/Application\ Support/VMware\ Tools/vmware-tools-daemon --cmd='disk.shrink'
```


1. Save it as disk-shrink.sh
2. Open terminal to the folder you saved it as and run:
`chmod +x disk-shrink.sh`
3. The run using:
`sudo ./disk-shrink.sh`

**You cannot have any snapshots when shrinking disks.**

**Comment by Yuri010** [comment]
Thanks for the script for shrinking the disks.
Ill try it out (should I change something about the dd command because my vmdk is 128GB max)

And thanks in general :)

**Comment by DrDonk** [comment]
The dd command should be OK but feel free to update the count parameter if you think you need.
