### ISSUE TITLE
Windows | Unlocker not searching parent directory for iso folder

### ISSUE THREAD

**Issue by asdfmonster261** [DrDonk/unlocker#5]
If you run unlocker.exe, the script will succeed with everything except copying the darwin isos, due to reason in title. 

If you manually copy the iso folder into the windows folder and run unlocker.exe, itll copy the isos correctly.

**Comment by DrDonk** [comment]
In the readme run it from the parent folder with .\windows\unlocker.exe.

**Comment by DrDonk** [comment]
Sorry accidentally closed this. For now follow the readme and I will add some additional logic in a new version to check current and parent folder.

**Comment by DrDonk** [comment]
Fixed in 4.1.1
