### ISSUE TITLE
GPU Acceleration?

### ISSUE THREAD

**Issue by MatthewStacy44** [DrDonk/unlocker#50]
I was wondering when will Unlocker potentially support Apple VGPU support? The reason why I am asking, is because the Darwin.iso only gets you up to 128 MB, when you can have more somehow. I wish you guys the best of luck and hopefully we can get a solution to "the new way to Hackintosh."

**Comment by DrDonk** [comment]
Not possible, it actually requires Apple hardware and macOS on host. In addition VMware have actually dropped support for it in Fusion as it doesn't work well.

**Comment by CodeGenStudio** [comment]
@DrDonk I hope I don't sound redundant, but do you know any hackintosh kernel ext/driver or something, that allows the VM to make use of the host GPU? Regardless if it is supported on real Macs or not? Or some other workaround? Not necessarily that this unlocker has to do it. Because my XCode simulator as frequent crashes because obv lack of 3D acceleration.

I tried asking this in Hackintosh reddit and even TonyMacx86 but they all have so dumb rule to not ask questions relating to macOS on Virtualbox or VMware, which is super annoying considering both as pretty much violating Apple's EULA and all that so what's the big deal. So I'm asking again here

**Comment by DrDonk** [comment]
I think KVM-QEMU on Linux can do this, but never tried it. I would start here:

https://github.com/kholia/OSX-KVM

This is a Linux only solution.

Also Nvidia did something with Hyper-V. Have a search on web for Nvidia Keppler and GPU passthru.

**Comment by MatthewStacy44** [comment]
@DrDonk, I was wondering what about the Darwin.iso? It makes the video ram go from 3MB to 128MB. Is there any way to get more video ram than 128MB using the Darwin.iso?

**Comment by DrDonk** [comment]
Nope and actually macOS guests ignore the setting. There was a post on VMware forums by Fusion product manager saying it isn’t used.

**Comment by CodeGenStudio** [comment]
> I think KVM-QEMU on Linux can do this, but never tried it. I would start here:
> 
> https://github.com/kholia/OSX-KVM
> 
> This is a Linux only solution.
> 
> Also Nvidia did something with Hyper-V. Have a search on web for Nvidia Keppler and GPU passthru.

Sad that it's a Linux only solution. My main workspace is Windows 10 so a Windows host solution is preferable.

That being said, Windows 10 runs on it's on hypervisor, which VMware makes some use of with many limitations (VMware themselves stated this in their Knowledge base). Features like nested virtualization and virtualized IOMMU are unavailable with this hyper-v + vmware combo. Do you think that, disabling Windows 10 hypervisor so VMware can get access to direct CPU virtualization technology (like Intel VT-x) can somewhat improve performance? I'm not an expert in these things but it something that occurred to me. I'm a little hesitant to disable the windows hypervisor, as it has a lot of benefits like windows sandbox as well as virtualization based security (VBS)

**Comment by DrDonk** [comment]
I do think the VMware hypervisor is better (they invented it for x86) and certainly makes more things available (cpuid masking..) over delegating to VMX mode to Hyper-V. However Hyper-V does have the benefits you suggested. I personally have never had the Hyper-V stuff on so can't really help with performance

Bottom line is I think the only way to know is for you to test it with your workload.

**Comment by CodeGenStudio** [comment]
@DrDonk

So just a quick update on this. I disabled Hyper-V services completely (it wasn't as hard as I thought) and although there is no acceleration, the graphics are FAR smoother - extremely usable. I tested this on an intel-i7 host CPU running Win 10, with Ventura Guest.

If you want, I can help make a guide or something on how to disable Hyper-V so people can have faster macOS VMs.

**Comment by DrDonk** [comment]
I have built a new utility called hostcaps to check if Hyper-V is running https://github.com/DrDonk/unlocker/wiki/hostcaps.

I would be happy to add to the wiki pages if you want to write something in Markdown on disabling Hyper-V. I can then reference that page ffrom the hostcaps one.

**Comment by kenmcd** [comment]
> I have built a new utility called hostcaps to check if Hyper-V is running https://github.com/DrDonk/unlocker/wiki/hostcaps.
> 
> I would be happy to add to the wiki pages if you want to write something in Markdown on disabling Hyper-V. I can then reference that page ffrom the hostcaps one.

How is hostcaps supposed to work?
When I run it on Windows 10 in a command window there is no output.
When I run it alone there is no output.

cpuid works and returns output in the window.
check, unlock, and relock all work as expected.

So what am I doing wrong?

**Comment by DrDonk** [comment]
I have no idea what I did building it for v4.2.4, but re-compiled and now works. I've attached a copy here. I modified the output as well to state that graphics may be affected.

Example output:
```
macOS Unlocker Host Capabilities
================================
© 2014-2023 David Parsons


Host CPU
--------
Name: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Vendor ID: Intel
CPU Family: 6 Model: 158 Stepping: 10

Host Report
-----------
AVX2 support:
        macOS 13 Ventura:  true
Hypervisor mode:
        Hypervisor Present: true
        Hypervisor String: Microsoft Hv
        Hypervisor ID: MSVM
        Hypervisor found:
                - CPUID masking may not work correctly
                - Graphics speed may be affected


Press Enter key to continue...
```

[hostcaps.exe.zip](https://github.com/DrDonk/unlocker/files/10474251/hostcaps.exe.zip)

**Comment by ghost** [comment]
Another issue is in the 3D settings, it says "3D acceleration is not supported in this guest operating system" when macOS is selected. Maybe it would be possible to get it work if you write custom driver for macOS and select guest OS as Windows 10/11 or Linux/Ubuntu to enable 3D settings? And can we get ideas from Ubuntu distros that automatically detects VM GPU?

**Comment by DrDonk** [comment]
Good luck with that. There is pretty much zero documentation on Apple GPU drivers.

This was partially solved on macOS with Apples paravirtualized GPU but that really hasn’t moved forward.

**Comment by CodeGenStudio** [comment]
> I have built a new utility called hostcaps to check if Hyper-V is running https://github.com/DrDonk/unlocker/wiki/hostcaps.
> 
> I would be happy to add to the wiki pages if you want to write something in Markdown on disabling Hyper-V. I can then reference that page ffrom the hostcaps one.

For sure, I would love to do that. I'll create the markdown and attach the text in this thread in a bit.

**Comment by DrDonk** [comment]
Great appreciate it.

**Comment by DrDonk** [comment]
Closing as no updates.
