### ISSUE TITLE
upgrade macos 13 error

### ISSUE THREAD

**Issue by datafeng** [DrDonk/unlocker#51]
vm16.2.4
macos12.5--->13 
reboot login error..

like this image:
[![zMY5VI.png](https://s1.ax1x.com/2022/11/20/zMY5VI.png)](https://imgse.com/i/zMY5VI)

**Comment by DrDonk** [comment]
Duplicate

https://github.com/DrDonk/unlocker/issues/47

**Comment by julianxhokaxhiu** [comment]
@DrDonk I've had the same issue today on a Linux installation, [used your instructions ](https://github.com/DrDonk/unlocker/issues/47#issuecomment-1326775639) on a Windows installation instead and it works on first shot ( [same ISO image](https://gist.github.com/julianxhokaxhiu/42332e67640daad8f18386eeec43ea73) used on both to start the installer ).

I also did try with your [bootable VMDK](https://github.com/DrDonk/unlocker/wiki/Create-a-bootable-macOS-Recovery-vIrtual-disk) on Linux and it shows the same behavior. Is anything different between Linux and Windows editions/unlockers?

The test was done on the same machine which has an i7-8550U, 16GB DDR4 RAM and a 256GB NVMe disk.

**Comment by DrDonk** [comment]
@julianxhokaxhiu can you open a new issue please? This one was closed as was AMD related. 

FYI patches are identical on Linux & Windows. More on a new issue.
