### ISSUE TITLE
Unable to select or go past anything above MacOS 11.1

### ISSUE THREAD

**Issue by Deathlife23** [DrDonk/unlocker#54]
Any clue why? I have VMWare Workstation 16.2.1 as the version.

**Comment by Deathlife23** [comment]
*16.1.2

**Comment by DrDonk** [comment]
Because that was the version available when 16.1.2 came out. It is perfectly useable with macOS 12 and 13 as was all Fusion had until last week and release of Fusion 13.

**Comment by SimPilotAdamT** [comment]
I checked, this is definitely an issue with Workstation 16 only (although I did not have that issue on 16.2.1). Workstation 17 has everything all the way up to 14 (Ventura), which is a borked version atm

**Comment by DrDonk** [comment]
Yes it's a non-issue and not patcheable so closing.
