### ISSUE TITLE
Workstation 17

### ISSUE THREAD

**Issue by mikeyo** [DrDonk/unlocker#55]
Is the new WS17 supported?

**Comment by SimPilotAdamT** [comment]
It works for me....

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: mikeyo ***@***.***>
Sent: Wednesday, November 23, 2022 2:19:29 PM
To: DrDonk/unlocker ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DrDonk/unlocker] Workstation 17 (Issue #55)


Is the new WS17 supported?
