### ISSUE TITLE
OSX10.9 can't install vmware tools on vmware16

### ISSUE THREAD

**Issue by haozia816** [DrDonk/unlocker#58]
The installer can't continue.
![image](https://user-images.githubusercontent.com/8665086/205003218-df764dc0-a0aa-4a2e-85a7-fa26afa458a8.png)

**Comment by DrDonk** [comment]
Try this:

1. Cancel "Install VMware Tools" from VMware menu if you started the install from the Workstation/Player menu
2. Manually add darwinPre15.iso to the virtual CD-ROM drive
3. Try again
 
If that does not work it will be a VMware issue.

**Comment by DrDonk** [comment]
@haozia816 Did this fix the issue?

**Comment by DrDonk** [comment]
No response so closing.
