### ISSUE TITLE
Ventura keep rebooting.

### ISSUE THREAD

**Issue by loudywen** [DrDonk/unlocker#59]
My setting
![image](https://user-images.githubusercontent.com/706038/205202525-131dce92-281e-498e-86bc-9e7f0ad87eef.png)

VMware version:
VMware Workstation 17

Issue:
![image](https://user-images.githubusercontent.com/706038/205202563-052ca66f-d40a-4267-bb7d-7c706197f215.png)

log and vmx:
[macOS 13.zip](https://github.com/DrDonk/unlocker/files/10137681/macOS.13.zip)

Also tested this setting from https://github.com/DrDonk/unlocker/issues/33

```
# >>> START <<<
# This spoofs CPUID as MacBook Pro (15-inch, 2018) - MacBookPro15,1
cpuid.0.ebx = "0111:0101:0110:1110:0110:0101:0100:0111"
cpuid.0.ecx = "0110:1100:0110:0101:0111:0100:0110:1110"
cpuid.0.edx = "0100:1001:0110:0101:0110:1110:0110:1001"
featMask.vm.cpuid.FAMILY = "Val:0x6"
featMask.vm.cpuid.MODEL = "Val:0x9e"
featMask.vm.cpuid.STEPPING = "Val:0x0a"
cpuid.brandstring = "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz"
cpuid.inhibitDarwinMasks = "TRUE"
board-id.reflectHost = "FALSE"
board-id = "Mac-937A206F2EE63C01"

# Throw VMware error if no AVX2 support in CPU
featMask.vm.cpuid.AVX2 = "Min:1"

# Ensure no boot loop due to macOS unsupported Intel e1000 NIC
ethernet0.virtualDev = "vmxnet3"
# >>> END <<<
```

**Comment by DrDonk** [comment]
This topic is now closed. There isn't a way to fix this. Please see 

https://github.com/DrDonk/unlocker/issues/47
