### ISSUE TITLE
[Feature Req] Should 'win-install.cmd' automatically copy the tools to the 'InstallPath' folder after 'gettools.py'? 

### ISSUE THREAD

**Issue by nguyenduy4321** [DrDonk/unlocker#6]
I compared your tool with others which add the command line `xcopy /F /Y .\tools\darwin*.* "%InstallPath%"` after running _gettools.py_

As the title I mentioned, should or not?

**Comment by DrDonk** [comment]
No it does not copy the isms and I removed it as makes no difference where it is stored as it is not automatically picked up by Workstation.
