### ISSUE TITLE
Unlocker V4.0 does not work for VMware Workstation Pro v16.2.1.18811642

### ISSUE THREAD

**Issue by AEROBATlCS** [DrDonk/unlocker#6]
Hello Friend! For some reason your solution doesn't work for VMware Workstation Pro v16.2.1.18811642 and earlier builds of version 16. Why is this happening? A message about the guest operating system pops up. AMD 5950X.
smc.version = "0" presented.
I understand this message (**The CPU has been disabled by the guest operating system. Power off or reset the virtual machine**.) is caused by VMware software? Does it depend on the mounted disk image?

**Comment by DrDonk** [comment]
This is because you are using an AMD CPU which native macOS does not support. The patches cannot fix this and you will need to look for macOS patches to run it on AMD.

You could ask here https://amd-osx.com/

**Comment by AEROBATlCS** [comment]
> This is because you are using an AMD CPU which native macOS does not support. The patches cannot fix this and you will need to look for macOS patches to run it on AMD.

Ready! Works fine!
Created a question with a description of the solution.
https://qna.habr.com/q/1100816

**Comment by DrDonk** [comment]
OK I was not aware that there was still an issue with the SMC setting. It is not something I can patch but I will add a note back into the readme about this workaround.

I am interested in what you used for the AMD CPU. Was it a specific macOS kernel patch or OCLP?

**Comment by DrDonk** [comment]
I will add some notes explaining changing the SMC version.

**Comment by AEROBATlCS** [comment]
I cannot say. These are just guesses. I can't say for sure.

**Comment by DrDonk** [comment]
OK, well thanks for pointing me to the web page.

**Comment by BKdilse** [comment]
I can confirm that the following worked for me on an AMD Ryzen 3900x, adding to the VMX:
```
cpuid.0.eax = "0000:0000:0000:0000:0000:0000:0000:1011"
cpuid.0.ebx = "0111:0101:0110:1110:0110:0101:0100:0111"
cpuid.0.ecx = "0110:1100:0110:0101:0111:0100:0110:1110"
cpuid.0.edx = "0100:1001:0110:0101:0110:1110:0110:1001"
cpuid.1.eax = "0000:0000:0000:0001:0000:0110:0111:0001"
cpuid.1.ebx = "0000:0010:0000:0001:0000:1000:0000:0000"
cpuid.1.ecx = "1000:0010:1001:1000:0010:0010:0000:0011"
cpuid.1.edx = "0000:0111:1000:1011:1111:1011:1111:1111"
```
