### ISSUE TITLE
Linux WS 17 - Long unresponsive periods when switching tabs

### ISSUE THREAD

**Issue by snhirsch** [DrDonk/unlocker#60]
Never saw this before, but since upgrading to WS 17 today and using the latest Unlocker release things go brain dead periodically and VMware does not switch out from the Mojave VM guest.  If I persist the entire VMware GUI stops responding.  After a few minutes it "wakes up" and finally switches.  

I had previously been using Unlocker 3.07 with no issues at all.  Should I revert?  It's unclear whether that older version even supports WS 17, however.

UPDATE: This seems somehow related to guest resizing!  After I resize the VMware window, the guest reverts to full resolution (everything too small rather than scaled) and the tab switching goes numb.

**Comment by DrDonk** [comment]
Unlocker 3 & 4 do exactly the same patches just 4 was a rewrite in Go as there were complaints about using Python. So there are no differences from that perspective. 

Nothing the patcher does would impact responsiveness so must be either a new VMware issue or something specific to your system.

**Comment by snhirsch** [comment]
I've done a bit more fiddling and believe I've narrowed the problem down.  Before installing I followed your advice and checked for a newer darwin.iso at Vmware's site.  There was a newer file, so I installed Vmware tools from that ISO.  Brief aside:  Even though the .iso file was in /usr/lib/vmware/isoimages, Vmware told me it was unable to find one on the server (?).  I had to mount it manually.  After a number of rounds of freezeups, I re-installed the guest tools from the .iso included in unlocker.  So far, no further problems. 

Isn't Vmware supposed to automatically find darwin.iso?

**Comment by DrDonk** [comment]
VMware only really does it on Fusion. It did start working in WS 16 but was broken in 15. Maybe it has regressed to old behaviour. I never found a simple way to fix it in WS 15.

Good you got it sorted. Are you happy close the issue?

**Comment by snhirsch** [comment]
Give it a day or so, if you wouldn't mind.  I'll update the issue whatever I find.

**Comment by DrDonk** [comment]
Sure NP.

**Comment by snhirsch** [comment]
After reverting the guest tools back to the 9/21/2022 darwin.iso distributed with unlocker I'm unable to reproduce the hangups in a day of bashing at it.  Would suggest that folks avoid the VMware-Tools-darwin-12.1.5-20735119 image that's currently offered on the Apple web site.  This may be particular to Mojave guests or something else unique about my system, so YMMV.
