### ISSUE TITLE
My mac ventura gets looped when booting vmware

### ISSUE THREAD

**Issue by Ayushprtp** [DrDonk/unlocker#64]
My mac ventura gets looped when booting vmware

https://user-images.githubusercontent.com/78673505/206089114-bd3fe028-3e7c-4718-ae8b-b07fb969b912.mp4

_Originally posted by @Ayushprtp in https://github.com/DrDonk/unlocker/issues/62#issuecomment-1340360573_

**Comment by Ayushprtp** [comment]
After installing mac I am getting this issue

**Comment by Ayushprtp** [comment]
[macOS 13.zip](https://github.com/DrDonk/unlocker/files/10172850/macOS.13.zip)

**Comment by DrDonk** [comment]
Please read https://github.com/DrDonk/unlocker/blob/main/README.md#macos-ventura-guests

You need to change the virtual network card:

`ethernet0.virtualDev = "e1000e`

to

`ethernet0.virtualDev = "vmxnet3"`

**Comment by Ayushprtp** [comment]
Still getting same error I installed ventura

https://github.com/DrDonk/unlocker/blob/main/README.md#macos-ventura-guests
In this page mentioned that to Please do not upgrade to Ventura at this time if you have AMD or Intel pre-Haswell CPUs.

**Comment by DrDonk** [comment]
I noticed you’ve got a Sandy Bridge CPU so I’m sorry you won’t be able to run Ventura.

My mistake as I missed that when I checked the vmware.log.

**Comment by Ayushprtp** [comment]
Thanks for help

**Comment by DrDonk** [comment]
Happy to look into it. Sorry there isn't a way for the unlocker to fix this.
