### ISSUE TITLE
0xc000003e error after installing unlocker for Workstation 16 in win10

### ISSUE THREAD

**Issue by RpiDude** [DrDonk/unlocker#7]
![IMG_20210921_205343261](https://user-images.githubusercontent.com/44663086/134173446-c0154b77-a7d9-4baf-8a8a-b8bed7c175d3.jpg)

any help would be greatly appreciated, there is 0 on this in google

**Comment by DrDonk** [comment]
Can you provide more info please? 

1. Did the unlocker installer run correctly?
2. Is it downloaded from the releases page on. this repo?
3. Is this error when starting VMware Workstation?


This errors commonly found when a system file has been corrupted or registry has a problem. The unlocker does not write to either system folders or the registry. Just wondering if something else has gone wrong on the system.

**Comment by RpiDude** [comment]
Thanks for the rapid response DrDonk.

1. Yes the installer ran fine and downloaded the addon pack fine

2. Yes it's downloaded from this repo

3. I will have to check tomorrow when I wake up to give you the exact ver number of win10 (on tje phone atm)

4. Yes, or any of the .exes related to Vmware, runs fine before unlocker, only occures after unlocker is done.

I shall return with more indepth info tomorrow when I wake up and maybe a video of the commandline window when Unlocker is being run.

**Comment by RpiDude** [comment]
Workstation 16.1.2-17966106

Windows 10 Pro

**Comment by RpiDude** [comment]
Is there any way to make the unlocker not redownload the .tar every time, and instead detect the completed .tar if I move it there?

**Comment by RpiDude** [comment]
Case closed without solving it, downgraded to Workstation 15 and ran paolos unlocker, appears to work.

0xc000003e error might be caused by a registry error that has to do with Vmwares network drivers.
