### ISSUE TITLE
RUNNING THE unlock.go SCRIPT

### ISSUE THREAD

**Issue by lovelaye4real** [DrDonk/unlocker#72]
I get this error:
Copying VMware Tools...
/tmp/go-build907371810/b001/iso/darwinPre15.iso -> /usr/lib/vmware/isoimages/darwinPre15.iso
Error copying darwinPre15.iso
/tmp/go-build907371810/b001/iso/darwin.iso -> /usr/lib/vmware/isoimages/darwin.iso
Error copying darwin.iso

**Comment by DrDonk** [comment]
Just download a release unless you want to build from source code.
https://github.com/DrDonk/unlocker/releases/tag/v4.2.4

**Comment by DrDonk** [comment]
@lovelaye4real Have you got this working?

**Comment by DrDonk** [comment]
No response so closing.
