### ISSUE TITLE
VMCorePkg

### ISSUE THREAD

**Issue by Lenovo035** [DrDonk/unlocker#73]
Hello, I need help from you I want to install macOS Ventura in vmware but after the installation macOS keeps restarting and now I saw on your site you uploaded a vmx-opencore I know there is no support from your site about this one whole files in vmx-opencore where do they belong and do you only have to copy the files after the installation of macOS or before that would be my question and if that works respect to you
Warm greetings

**Comment by DrDonk** [comment]
You just add the VMDK to the guest using the VMware UI add device and use add existing hard drive. You then select that virtual drive as the boot drive either in VMware UI or boot to EFI and select it. They can be used to boot at anytime pre or post install.

I should point out this probably won't solve your problem as this was just a sample for others to build upon and does not do anything to fix Ventura. I suggest you read my wiki page on Ventura. https://github.com/DrDonk/unlocker/wiki/macOS-Ventura-Guests

**Comment by DrDonk** [comment]
@Lenovo035 Any updates? Are you OK with the explanation?

**Comment by Lenovo035** [comment]
Hello, unfortunately it didn't work on ivy bridges
and what's strange is that I still have a Haswell desktop PC with an Intel Core i5 and it doesn't work there either. I get to the Apple configuration menu and then it suddenly starts again

**Comment by DrDonk** [comment]
Do you mean the boot selector? Do you have a macOS system attached or an installation image? This is just a booter it does not have any macOS images.

**Comment by Lenovo035** [comment]
Hello, on my Haswell PC
I proceeded like this, I created a macOS Ventura iso, then I inserted the iso into Vmware and installed macOS as normal, 4GB Ram, 2 CPU cores and the system keeps restarting after a certain time, but I change it to 1 CPU core system but not liquid because I'm in Vesa mode and when I install Vmware the installation fails.
I'll let it be, nothing works, maybe there'll be a solution until then, I'll just wait.

**Comment by DrDonk** [comment]
Someone has made progress on this. https://github.com/macchrome/compilers/releases/

**Comment by Lenovo035** [comment]
Hello, I looked at the link but I can't do anything with it because I'm not very familiar with the topic.

**Comment by DrDonk** [comment]
TBH I’m not sure how to make this work with the components needed from the M1/2 version of macOS. I understand what the issue is and how it may be resolved but not the mechanics of actually doing it.

**Comment by DrDonk** [comment]
I also just read OpenCore won’t support Ventura on pre-Haskell

https://dortania.github.io/OpenCore-Install-Guide/extras/ventura.html#table-of-contents
