### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Florin9doi** [DrDonk/unlocker#74]
Suggestions:
* cpuid and hostcaps to wait for a key press before exiting
* https://github.com/DrDonk/unlocker/blame/main/CHANGELOG.md#L3
```diff
- All dates are UK format.
+ All dates are DD/MM/YY format.
```
* Rename [Create-a-bootable-macOS-Recovery-vIrtual-disk](../wiki/Create-a-bootable-macOS-Recovery-vIrtual-disk) to (...)-virtual-disk
* https://github.com/DrDonk/unlocker/wiki/Create-a-bootable-macOS-Recovery-vIrtual-disk#:~:text=Aftr%20the%20tool%20has%20finished

**Comment by DrDonk** [comment]
I’ve changed date but kept UK as well in changelog.
Fixed the typo in Wiki.

I’ll add wait for key to hostcaps, but cpuid really needs full command line to use properly. I modified it for some VMware specific formats and I expect it will need flags and other parameters passed to it.

Thanks for picking up on the issues.

**Comment by DrDonk** [comment]
Updated hostcaps to wait for a keypress. It will be in the next release.

**Comment by Florin9doi** [comment]
> Fixed the typo in Wiki.

The wiki main page still points to the previous page: https://github.com/DrDonk/unlocker/wiki#:~:text=macOS%20Guest%20Debugging-,macOS%20Recovery,-Templates

Thank you

**Comment by DrDonk** [comment]
I forgot the main and index pages. One of those days!

**Comment by DrDonk** [comment]
Done now.
