### ISSUE TITLE
How do I install Mac OS in VMware workstation pro?

### ISSUE THREAD

**Issue by CattopyTheWeb** [DrDonk/unlocker#75]
I have run your unlocker but I don't know what to do next. As I understand I should get a Mac OS ISO but from where?
Please help me! I'm new to this.

**Comment by DrDonk** [comment]
This is for issues with the unlocker code I suggest you go ask on some forums, such as Insanelymac, they will have threads to help you out.

**Comment by CattopyTheWeb** [comment]
I have asked someone on discord in the Hackingtosh server but he didn' respond. That's why me asking here.

**Comment by DrDonk** [comment]
Try Insanelymac as I can’t help here, this is an issue tracker for code, I spent many years answering these questions on that forum but I know there are people there that can help. I’m not pointing to ISOs etc here for obvious reasons.

Google will also help for example https://techrechard.com/how-to-install-macos-monterey-on-vmware-on-windows-pc/.

**Comment by CattopyTheWeb** [comment]
Thank you, that website helped me set up the Mac OS in VMware.
