### ISSUE TITLE
Unable to launch the vmware after unlock it on Windows

### ISSUE THREAD

**Issue by SamLam140330** [DrDonk/unlocker#76]
After unlocking the VMware, it is unable to launch the app with the error: Entry Point Not Found
Even though I have relocked the VMware, it also comes with this error.

![Screenshot_20230116_045006](https://user-images.githubusercontent.com/48656764/212566621-199a3275-e203-47b0-afb3-de5b9d4baf51.png)

Any solutions? Thank you

**Comment by DrDonk** [comment]
Interesting as the unlocker does not touch the vmwarecui.dll. I suggest you first repair the VMware installation using the VMware installer.

I would also remove any backup folders in the unlocker directory to reset everything back to a known state.

Then can you answer the following questions please?

- Host OS
- VMware product and version
- Unlocker version

Finally if VMware is working correctly run the unlock command and capture the output and paste into the issue.

**Comment by SamLam140330** [comment]
Thank you for the reply
I will reinstall the app, lock it again, and capture the output later

>Then can you answer the following questions please?
> * Host OS

Windows 11 22H2 - 22621.1105

> * VMware product and version

VMware Workstation 17 Pro - 17.0.0 build-20800274

> * Unlocker version

Unlocker 4.2.4

**Comment by SamLam140330** [comment]
I have reinstalled the app and used the unlocker to unlock it. It seems no error this time
