### ISSUE TITLE
Upload speed

### ISSUE THREAD

**Issue by mdima** [DrDonk/unlocker#77]
Hello,
   when I test the network connection speed I have a very low upload speed, which brings to network instability and very long transfer times. 

Am I the only one who has this issue? 

Thanks

![speedtest](https://user-images.githubusercontent.com/1006461/212654488-c670554f-d063-462d-b663-1f41a10a0206.png)

**Comment by DrDonk** [comment]
This is not an unlocker issue. This will be VMware and possible their driver.

**Comment by mdima** [comment]
@DrDonk I agree... just I can't ask assistance to VMWare for this, just wanted to share this issue and see if I am the only one or someone else found a solution. 
Thanks anyway.

**Comment by DrDonk** [comment]
I understand but I’m now keeping the issues only for bugs with unlocker and testing new features. Can I suggest somewhere like Insanelymac to ask the question?

**Comment by mdima** [comment]
Thanks, I will have a look at that site. 
Have a great day,
Michele
