### ISSUE TITLE
Question about Unlocker for DrDonk

### ISSUE THREAD

**Issue by LFU-SysTech** [DrDonk/unlocker#78]
Hello DrDonk

I am a trainee systems engineer from Switzerland and will graduate this summer. 

For my final project, I have decided to build a virtualised MacOS infrastructure for customer support on different Mac OS releases for our company.

Since Mac OS is not compatible with Windows and this project will be done on ESXi i.e. Windows, I am facing a good challenge.

I would like to know more about the patch you have created, the technique used and the technical solution to overcome the problem.

You are welcome to reply here or to my mail.

E-mail: 
luiz.utiger@aac.ch

Thank you very much for your feedback and help.

Kind regards
LFU-SysTech

**Comment by DrDonk** [comment]
Sure I'll email you.

**Comment by DrDonk** [comment]
Email sent and we'll continue there.
