### ISSUE TITLE
I can't exceed more than 8 core

### ISSUE THREAD

**Issue by MODE83-PROJET-DEV** [DrDonk/unlocker#79]
Hello,

I have bugs when I choose more than 8 logical cores in vmware:

MacOs does not start at all and in addition the parameters are not taken into account, even with 20 logical cores, I do not exceed 8 cores.

I wanted to know if this was normal and found. And see if you have any thoughts.

Config :
Windows 11 Pro 22H2
Intel Core i5-13600KF
32 Go RAM DDR5

Thanking you.

**Comment by DrDonk** [comment]
I think that is a limitation of VMware and cannot be changed.

**Comment by DrDonk** [comment]
Well I checked and latest versions support 32 cores. Possibly macOS?

**Comment by MODE83-PROJET-DEV** [comment]
thank you for the answer

Maybe MacOS, 
The "mac pro" embed read a 20 core in their hardware
I saw in the vmx file that there are two references :
hw.model = "MacPro2022"
board-id = "Mac-7DF21CB3ED6977E5"

Can this influence macOS on this parameter? I thought that depending on the model it can block.

But that's just a guess.

**Comment by MODE83-PROJET-DEV** [comment]
I tried, but it didn't work.

I'll leave this post in case anyone else has an idea.

thanks

**Comment by DrDonk** [comment]
Can you **attach** the VMX file and a vmware.log file to the issue? Maybe something restricting it in settings. I have a suspicion that VMware is limiting the core count for macOS guests.

**Comment by MODE83-PROJET-DEV** [comment]
Hi,

I dropped the idea of ​​virtualizing macOS, as it is not usable.

I found an easier solution, using a real mac. which will be more efficient than virtualization.

Coming back to the limitation, vmware explains it concretely. It will no longer have support for macOS and will no longer be supported as well as vmware tools to manage drivers.

MacOs also has its own limits and on a somewhat obscure forum I got information that Apple limited the use of VMs on their OS, this has to be confirmed of course.

I've really tried everything, I don't exceed 8 cores

I kept the prod machine that I used until now, I don't know if it will help you.

But you have the files

Here are the various config tested

Setup:
i5 13600KF (14 CORE, 20TH)
32 GB DDR5
Perf: very degraded, impossible to use
-------------

i7-7700 (4 CORE - 8 TH)
16GB DDR4
Perf: usable but not comfortable.
-------------

AMD Ryzen 3700X (8 CORE - 16 TH)
32GB DDR4
Perf: Not usable with unlocker 3 and 4

Hope this helps, good luck


[vmware.log](https://github.com/DrDonk/unlocker/files/10675728/vmware.log)

[I've added the settings as a file, just makes the issue easier to read - Dave]
[issue_29_vmx.txt](https://github.com/DrDonk/unlocker/files/10676194/issue_29_vmx.txt)

**Comment by DrDonk** [comment]
Well I would agree with you. I have real Apple hardware for development and other resource intensive processes.

FYI - On Intel Macs the Apple EULA does not have any restrictions on CPUs etc., only that you can run a maximum of 2 copies on the hardware. And for VMware definitely seeing the end of support on ESXi for macOS. The Fusion PM has started though that he expects that not to change for VMware Fusion.

**Comment by MODE83-PROJET-DEV** [comment]
Ok that's good to know.

It was nice talking with you.
 
thank you for your information

Good luck for the future
