### ISSUE TITLE
Any chance of compatibility with Ryzen and Workstation 16.xx?

### ISSUE THREAD

**Issue by hindsa-nabeel** [DrDonk/unlocker#8]
Any chance of releasing a version that is also compatible with VMware Workstation 16.xx on AMD Ryzen?

**Comment by DrDonk** [comment]
That's not what the unlocked can do.  You will need  an AMD kernel and some patches to make that work.

**Comment by hindsa-nabeel** [comment]
But the unlocker works fine with VMware Workstations 15.1 and lower?

**Comment by DrDonk** [comment]
The unlocker does not and has never had anything in it to work with AMD. I've been working on it since 2007 when I first got it working.

**Comment by hindsa-nabeel** [comment]
Thanks DrDonk,
There were reports in page 3 of the link I provided earlier stating that it could work if certain parameters were set in the VMX file, such as this:

add the below to your .vmx config file for you AMD system, what version of VMWare are you using and what macOS are you attempting to spin up? im using unlocker-master which the script echos ver: 3.0.2
smc.version = "0"
cpuid.0.eax = "0000:0000:0000:0000:0000:0000:0000:1011"
cpuid.0.ebx = "0111:0101:0110:1110:0110:0101:0100:0111"
cpuid.0.ecx = "0110:1100:0110:0101:0111:0100:0110:1110"
cpuid.0.edx = "0100:1001:0110:0101:0110:1110:0110:1001"
cpuid.1.eax = "0000:0000:0000:0001:0000:0110:0111:0001"
cpuid.1.ebx = "0000:0010:0000:0001:0000:1000:0000:0000"
cpuid.1.ecx = "1000:0010:1001:1000:0010:0010:0000:0011"
cpuid.1.edx = "0000:1111:1010:1011:1111:1011:1111:1111"
featureCompat.enable = "FALSE"

**Comment by DrDonk** [comment]
I helped with those parameters but not very stable results and the people who used it abandoned it. Also this was not part of the unlocker and there is no way to patch that into VMware code.
