### ISSUE TITLE
ESXi 6.5 or 7 - Unlocker 2.0.9RC Download link needed

### ISSUE THREAD

**Issue by mmccollum2** [DrDonk/unlocker#80]
Would you be able to comment or help/link to the Unlocker 2.0.9RC downloader for ESXi 6.5? Trying to get this working and noticed that only 2.0.8 is available for download from the insanelymac site, and your git here starts at v4 but no more listing of ESXi compatibility.

[This comment](https://www.insanelymac.com/forum/topic/303311-workstation-1112-player-712-fusion-78-and-esxi-6-mac-os-x-unlocker-2/?do=findComment&comment=2396315) had mentioned it worked and wondered if you still had it?

(Or if I'm missing something and this repo works with ESXi 6 and above then please let me know

Thank you so much!

**Comment by SimPilotAdamT** [comment]
Iirc (I could be wrong about this) this project is technically a fork. There is no history of anything pre version 4.0. Are you really unable to find anything?

@DrDonk am I wrong?

**Comment by mmccollum2** [comment]
Of course, as soon as I post an issue,[ found a blog](https://www.nakivo.com/blog/run-mac-os-on-vmware-esxi/) that has an edit about another[ unlocker (v300)](https://www.insanelymac.com/forum/files/file/964-macos-unlocker-v30-for-vmware-esxi/) to support ESXi 6.5 and 6.7. Checking now!

**Comment by mmccollum2** [comment]
If this helps anyone, if you have ESXi 6.5 or 6.7 and want to run MacOS Ventura, and with the unlocker v2.x you're getting this error `Failed - Transport (VMDB) error -45: Failed to connect to peer process.`

Then uninstall any unlocker patches and here's some guidance for you!

[Good blog to follow for steps](https://www.nakivo.com/blog/run-mac-os-on-vmware-esxi/)
[All/Any MacOS ISO images that you need, ready for download](https://archive.org/details/macos-collection)
[Unlocker 3.0.0 that works with ESXi 6.5 and 6.7](https://www.insanelymac.com/forum/files/file/964-macos-unlocker-v30-for-vmware-esxi/)

Annnnd   ESXi 7.0 and 7.0 U1 (7.0.1) [blog ](https://vmscrub.com/installing-macos-12-monterey-on-vmware-esxi-7-update-3/#)and [git](https://github.com/erickdimalanta/esxi-unlocker)

Good luck!

**Comment by DrDonk** [comment]
I can give it to you from my archives but it needs a change because it was unreliable and caused some issues. I now know what that is and can change it. I would not use the one out there.

**Comment by DrDonk** [comment]
Here is a hacked V3 called 3.9.9 to mitigate the issues there were on ESXi 6 with previous versions. You will need to re-run this when you patch or update the ESXi server software, the same as the supported v4 esxi-unlocker on ESXi7 & 8.

Note I won't be taking issue on this and I am not in a position to spend any time on it. So it's an "as-is" release.

1. Upload to ESXi Datastore
2. `unzip esxi-unlocker-3.9.9.zip`
3. `cd esxi-unlocker-3.9.9`

To install run & then reboot:

`esxi-install.sh`

To uninstall run & then reboot:

`esxi-uninstall.sh`

[esxi-unlocker-3.9.9.zip](https://github.com/DrDonk/unlocker/files/10465910/esxi-unlocker-3.9.9.zip)

**Comment by DrDonk** [comment]
> Iirc (I could be wrong about this) this project is technically a fork. There is no history of anything pre version 4.0. Are you really unable to find anything?
> 
> @DrDonk am I wrong?

I have the V2 and V3 in a private GIT repo after I retired from Insanelyemac (I was Donk over there) so they do still exist. I pulled V3 for ESXi after some heads up about how it worked, from trusted sources, and that's why there is now an esx-unlocker V4 here https://github.com/DrDonk/esxi-unlocker

This unlocker repo was created for the Go language port for Workstation and Player as ESXi is still Python based so split the code out.

**Comment by DrDonk** [comment]
No updates so closing

**Comment by mmccollum2** [comment]
Awesome! Thank you for the help on this and supplying the newer versions of this. Understood this isn't supported. Cheers.
