### ISSUE TITLE
Remove "Press Enter key to continue..."

### ISSUE THREAD

**Issue by KoalafiedDev** [DrDonk/unlocker#82]
Can the "Press Enter key to continue..." at the end of the script be removed (or ignored with a parameter). I can't silent install the script this way.

**Comment by DrDonk** [comment]
Set environment variable:

UNLOCK_QUIET=1

**Comment by Leander013** [comment]
Thank you. worked like a charm.

**Comment by KoalafiedDev** [comment]
Thank you. worked like a charm.
