### ISSUE TITLE
Download links without registration

### ISSUE THREAD

**Issue by BeJoNe** [DrDonk/unlocker#83]
there are two entry points where you can download the neccessary files like the "in app update" function:

**https://softwareupdate.vmware.com/cds/vmw-desktop/**

eg. latest Linux&Windows Workstation
https://softwareupdate.vmware.com/cds/vmw-desktop/ws/17.0.1/21139696/

and the MacOS tools (darwin) for running on non-Mac hosts:
https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.1.0/13668589/packages/

or latest MacFusion
https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/13.0.1/21139760/universal/core/

also there is a tools distribution website:
**https://packages.vmware.com/tools/releases/latest/**

all without registration or ads..

**Comment by DrDonk** [comment]
OK some of those do not give you a full installer, and the packages URL is only for Linux. I have listed download ,inks in the readme that do not require logins except the tools.

**Comment by BeJoNe** [comment]
> OK some of those do not give you a full installer, and the packages URL is only for Linux. I have listed download ,inks in the readme that do not require logins except the tools.

The 620MB "full installer" contains **all tools** - which nearly nobody needs.. the product itself is about 260MB

https://packages.vmware.com/tools/releases/latest/windows

**Comment by DrDonk** [comment]
OK that's new, thanks. I usually release a new version of unlocker with the latest tools, but  I was told recently that 12.1.5 may cause problems on macOS guests, so might be best sticking to previous release which is what I am still using in the unlocker.

**Comment by BeJoNe** [comment]
Well, you provide the darwin-iso files within your workspace - very risky..
Instead you could open the web-browser with the download url:
https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.1.0/13668589/packages/

just wanted to help :)

**Comment by DrDonk** [comment]
It's really not a big deal I've been developing and supporting various unlockers since 2007 and never been an issue. Apple certainly does not go after people or projects unless you try and charge for the work.

**Comment by BeJoNe** [comment]
> It's really not a big deal I've been developing and supporting various unlockers since 2007 and never been an issue. Apple certainly does not go after people or projects unless you try and charge for the work.

It's not Apple - but you are distributing VMWare product content :-\

**Comment by DrDonk** [comment]
OK I'm going to stop this here. I've removed the comments highlighting your concern as it just advertises the situation.
