### ISSUE TITLE
Help Wanted - New Maintainer

### ISSUE THREAD

**Issue by DrDonk** [DrDonk/unlocker#85]
I have decided after 15 years of working on this code in one form or another to hand it off to a new maintainer.

There are a few reasons for this:

1. I have actually retired in real life from the software industry after 34 years working in development and have new ambitions for the future
2. I'm moving to Apple Silicon and will not have a system to test this code moving forward
3. It's likely that the code will enter a maintenance only phase with the transition to Apple Silicon for macOS and VMware Fusion

There are over 200 forks of the code and I hoping one of those who forked it would look after it moving forward. Whoever takes it on would need to be happy to also look after the ESXi Unlocker as well. It's the same patches just  different programming languages.

If you are interested please reply to this issue.

**Comment by DrDonk** [comment]
Obviously nobody interested so closing. I have a new project which achieves macOS on VMware using OpenCore which also fixes things that are not fixable in the unlocker code.

It involves little code so maybe there would be more support to help with that.

**Comment by DakotaCodes00** [comment]
Hey @DrDonk I'd be willing to keep your repo maintained or help with your OpenCore workaround depending on what you would like to focus on. I'm pretty new to the whole developer thing ,I work as a Pentester although I am quite proficient at programming and I'm only 22 but I do have the skillset to learn fast

Let me know if I can help you out :)

Have a wonderful day and I wish you all the best in your endeavors and that you enjoy your retirement, you've earned it!

**Comment by DrDonk** [comment]
@its-romo Thanks for wanting to help out. I think the OpenCore approach is the way forward as a few folks have used it to run things not possible with unlocker such as Ventura on AMD CPUs. Currently the only code for new OC project is to generate config.plists and currently just Shell scripts and Jinja2 templates. And of course happy if you want to look after the Python and Go for the WKS and ESXi unlockers. There is a wiki page which explains what the unlocker actually does.

[https://github.com/DrDonk/unlocker/wiki/Patches](url)

I'm busy for a few days, but I'll ping you here next week to work out how to move forward.

**Comment by SimPilotAdamT** [comment]
I would have stepped up to help, and might do later on, but my contributions are just to the build shell scripts and file renaming. I reckon I will actually stuff, so we'll see...

I'll keep maintaining the AUR packages ofc.

**Comment by DakotaCodes00** [comment]
@DrDonk Awesome! I'll help out where I can with the OC project and get started looking through the wiki and understanding how the unlocker actually works 👍 

Not to worry about being busy I understand, I'm also quite busy at the moment so not to worry :)

**Comment by DakotaCodes00** [comment]
@SimPilotAdamT I'm sure any help is welcome, we all can play a part! :)

And thank you for maintaining the AUR packages! I used to be a hardcore Arch fan and I loved what you and all the other maintainers allowed Arch to achieve with the AUR platform <3

(I say "used to" because unfortunately I've been needing to run windows more and more for business etc and I reluctantly made the choice to switch to it as my host OS since I didn't have enough computing power to run it as a vm the whole time) :(

**Comment by DrDonk** [comment]
Hi. I’ve had a cold so bit late in replying. We need to find a way to chat. Any preferences?
