### ISSUE TITLE
AUR Build Process

### ISSUE THREAD

**Issue by DrDonk** [DrDonk/unlocker#86]
@SimPilotAdamT - I have made a cosmetic change where I swapped the meaning of build and dist folders in the build scripts. It was really to scratch an itch I had but I guess it will mean you need to look at the AUR  build process. I suspect it's not a big deal as looks like you have an AUR specific build process, but worth a check.

Yep it's a bit OCD but I am trying to clean everything up as I want to handoff to anew maintainer, if I can find a volunteer.

**Comment by SimPilotAdamT** [comment]
I am so sorry I didn't see this.

Yeah I noticed that, all of my PKGBUILDs have been updated accordingly
