### ISSUE TITLE
./unlock: 1: Syntax error: "(" unexpected on Debian 11

### ISSUE THREAD

**Issue by earthmoon** [DrDonk/unlocker#87]
***
# IMPORTANT
Please note this is not a discussion forum for help on running macOS, finding the installation images etc.
Also please checkout the wiki https://github.com/DrDonk/unlocker/wiki as it may answer your question.
***

**Describe the bug**
.
When I run **unlock** script on Debian 11, it returns:
> /unlock: 1: Syntax error: "(" unexpected

**To Reproduce**
1. Go to folder extracted 
2. run commands: sudo sh ./unlock
3. the error will show

**Expected behavior**
I hope it would unlock the vmware for macos

**Screenshots**
![Screenshot from 2023-02-06 08-02-36](https://user-images.githubusercontent.com/45897471/216978628-936ad06b-fae9-4073-8b5f-b6b7992bd8a7.png)

**Desktop (please complete the following information):**
 - Debian 11

**Additional context**
None

**Comment by DrDonk** [comment]
Try just:

`sudo ./unlock`

The unlocker is a Go compiled binary file not a shell script.

**Comment by earthmoon** [comment]
> Try just:
> 
> `sudo ./unlock`
> 
> The unlocker is a Go compiled binary file not a shell script.

> sudo: ./unlock: command not found

**Comment by DrDonk** [comment]
What are the contents of the folder with the unzipped files?

**Comment by earthmoon** [comment]
> > Try just:
> > `sudo ./unlock`
> > The unlocker is a Go compiled binary file not a shell script.
> 
> > sudo: ./unlock: command not found

I download it from [here](https://github.com/DrDonk/unlocker/releases/tag/v4.2.4)

**Comment by DrDonk** [comment]
That's fine. Can you send me the list of files after you unzipped the download? Use terminal and ls command

**Comment by earthmoon** [comment]
> That's fine. Can you send me the list of files after you unzipped the download? Use terminal and ls command

> CHANGELOG.md  iso  LICENSE  linux  README.md  templates  windows

It seems right.

**Comment by DrDonk** [comment]
OK so do this please:

```
cd linux
ls -l
```

and send me the output

**Comment by earthmoon** [comment]
> OK so do this please:
> 
> ```
> cd linux
> ls -l
> ```
> 
> and send me the output

> check  cpuid  hostcaps  relock  unlock

These

**Comment by DrDonk** [comment]
No please run it exactly as I asked.

cd linux
ls -l

**Comment by earthmoon** [comment]
> No please run it exactly as I asked.
> 
> cd linux ls -l

Sorry, Now I do as you asked:

> 
>  total 9564
> -rw------- 1 zeng zeng 2555170 Dec 21 11:35 check
> -rw------- 1 zeng zeng   77360 Dec 21 11:35 cpuid
> -rw------- 1 zeng zeng 2088148 Dec 21 11:35 hostcaps
> -rw------- 1 zeng zeng 2318623 Dec 21 11:35 relock
> -rw-rw-rw- 1 zeng zeng 2745387 Dec 21 11:35 unlock

**Comment by DrDonk** [comment]
right the executable bit has somehow been removed. Type this in the terminal in the linux folder:

`chmod +x *`

the try running the command again:

`sudo ./unlock`

**Comment by earthmoon** [comment]
> right the executable bit has somehow been removed. Type this in the terminal in the linux folder:
> 
> `chmod +x *`
> 
> the try running the command again:
> 
> `sudo ./unlock`

Thanks for your help.**zip** and **rar** can't save the executable bit. If save them as **tar.gz**, it would not have this error.

**Comment by earthmoon** [comment]
> right the executable bit has somehow been removed. Type this in the terminal in the linux folder:
> 
> `chmod +x *`
> 
> the try running the command again:
> 
> `sudo ./unlock`

This way works well.

**Comment by DrDonk** [comment]
Actually the zip file does have the executable bits (I check each release) and I'm not sure what happened to your system. I don't use TGZ as 95%+ users as on Windows and it's a non-native format.

**Comment by earthmoon** [comment]
> Actually the zip file does have the executable bits (I check each release) and I'm not sure what happened to your system. I don't use TGZ as 95%+ users as on Windows and it's a non-native format.

How about make the Linux folder to .tar.gz? And still make the all files in a .zip or .rar file. The Linux users can use .tar.gz without any problem with the permission errors and the Windows users can unzip them as before.

**Comment by DrDonk** [comment]
OK done for the next release.

**Comment by earthmoon** [comment]
> OK done for the next release.

Thanks a lot.
