### ISSUE TITLE
Got passed Ventura bootloop in VMware Workstation 16.2.4 on AMD CPU.

### ISSUE THREAD

**Issue by vsr3y** [DrDonk/unlocker#89]
@DrDonk How can I contact you personally? I'd like to discuss and iron out my methods before sharing everything.

Will update soon.

**Comment by DrDonk** [comment]
That's interesting.

I have created an OpenCore disk that boots Ventura on AMD. Maybe we have hit on a couple of solutions, and I need someone who can test it.


Email: d_a_v_e_@_d_a_v_e_p_a_r_s_o_n_s_._n_e_t

**Comment by DrDonk** [comment]
Here's the OC vmdk zipped. Can you try that out please? Use it to boot Ventura.
[opencore.vmdk.zip](https://github.com/DrDonk/unlocker/files/10802133/opencore.vmdk.zip)

**Comment by caiocost** [comment]
I have an AMD and trying to make it pass bootloop, if i can help with something

**Comment by natman101** [comment]
I gave it a red hot crack but unfortunately it didn’t work for me. Running Ryzen 5800x.
I ended up back in a bootloop. I’ll preface this with, I’m new to all of this but happy to continue testing if you would like me to.

**Comment by DrDonk** [comment]
There is something coming but not quite ready. It is not the unlocker but a new project that can be used without unlocking VMware. I may need a few testers when I’m ready. I need to write up how to use it.

**Comment by DrDonk** [comment]
Closing as testing is underway and not an unlocker issue
