### ISSUE TITLE
The auto-unlocker fails. Don't recommend https://github.com/paolo-projects/auto-unlocker 

### ISSUE THREAD

**Issue by PredragBoksic** [DrDonk/unlocker#9]
The other project that you recommend, renders the VMware unusable permanently even though the original Unlocker in Python was uninstalled. Windows 10 and Vmware 16.1 were installed.

**Comment by hindsa-nabeel** [comment]
What is the platform setup it failed with?

**Comment by PredragBoksic** [comment]
Windows 10 / Vmware 16.1 roughly.

**Comment by hindsa-nabeel** [comment]
If your hardware is AMD, then you need VMware Workstation 15.1 or lower.

Any way, I tried the latest compilation from DrDonk and it works fine (VMware Workstation 16.1.2/Windows 10 19044/Intel i7).

Previously I tried Auto Unlocker and it worked fine! However, I just noticed that the latest is the fourth iteration of Unlocker.exe. Here are the four:
https://github.com/paolo-projects/auto-unlocker/releases

**Comment by DrDonk** [comment]
All software has issues. Mine has had issues in the past and things are usually fixed if possible. I'm not comfortable criticising someone else's hard work.
