### ISSUE TITLE
[windows] Unable to patch because not all required services is stopped

### ISSUE THREAD

**Issue by r4sas** [DrDonk/unlocker#9]
```
> unlocker.exe uninstall
Unlocker 4.1.1 for VMware Workstation/Player
============================================
© 2014-2022 David Parsons

VMware is installed at:  C:\Program Files (x86)\VMware\VMware Workstation\
VMware version:  17198959

Stopping VMware services and tasks...
Stopping service  VMAuthdService
panic: Control(VMAuthdService) failed: A stop control has been sent to a service that other running services are dependent on.

goroutine 1 [running]:
github.com/drdonk/golocker/vmwpatch.svcStop({0x1027280, 0xe})
        /Users/dave/Projects/lang-go/golocker/vmwpatch/vmw_windows.go:223 +0x1f9
github.com/drdonk/golocker/vmwpatch.VMWStop(0xc0000de000)
        /Users/dave/Projects/lang-go/golocker/vmwpatch/vmw_windows.go:71 +0xc5
main.main()
        /Users/dave/Projects/lang-go/golocker/command/unlocker.go:73 +0x2c5
```
OS: Windows 10 21H1

**Comment by one80two** [comment]
hei. fixed it by first disabling all VMWare services in `services.msc` (not sure it was required actually) and then going into my VMs directories (mainly the suspended ones) and removing all directories/files that have the `.lck` extension. note that you need to set the services back to Automatic after running the unlocker. hope it helps :D

**Comment by r4sas** [comment]
That's not way how it must be done.

**Comment by DrDonk** [comment]
Unfortunately not enough info here to diagnose what happened. I suspect that VMware was still running or VMs running in the background. I will close this unless there is more information available.

**Comment by r4sas** [comment]
Isn't application must close everything automatically (like how it has been done with previous version of tool with cmd batch)? How I can gather more information?

**Comment by DrDonk** [comment]
Can you open a Windows PowerShell prompt and run this command please?

`Get-Service -Name VMAuthdService -DependentServices`

The output should show what is preventing VMAuthdService from stopping.

**Comment by r4sas** [comment]
```
> Get-Service -Name VMAuthdService -DependentServices

Status   Name               DisplayName
------   ----               -----------
Running  VMwareHostd        VMware Workstation Server
```

No VMs running at patching time.

So I think order here must be changed:
https://github.com/DrDonk/golocker/blob/dd119cb6fb5e82d91757874c63b84b839f08280a/vmwpatch/vmw_windows.go#L71-L72

**Comment by DrDonk** [comment]
Yep that's my mistake. I forgot the ordering when I wrote it, and tested against 16.2 which drops the Workstation Server code.

I will setup a test system and fix the code.

**Comment by DrDonk** [comment]
Please try v4.1.2 https://github.com/DrDonk/golocker/releases/tag/v4.1.2

**Comment by r4sas** [comment]
Everything works correctly now. Thanks.
