### ISSUE TITLE
Constant Bootloop.

### ISSUE THREAD

**Issue by stxrzdxrtz** [DrDonk/unlocker#90]
Hello, I am writing this because I am experiencing problems with installing macOS. My host OS is Ubuntu 22.04 LTS and the guest OS is macOS 10.12. I was going to run macOS 10.14 but it bootlooped and I thought it was just the iso file so I went for macOS 10.12 but the same problem occurred. It goes to the apple logo and the line appears but then yellow text pops up. I don’t know what to do if it’s a host OS issue or VMware Player.

**Comment by DrDonk** [comment]
Please attach a copy of the vmware.log file for the VM. Also run the check program in the unlocker folder and post results.

**Comment by gofmt** [comment]
I have the same problem

### Debian
Debian GNU/Linux bookworm/sid

### VMware

VMware® Workstation 17 Pro 
17.0.0 build-20800274

### Checker
```text
Checker 4.2.5 for VMware Workstation/Player
============================================

VMware is installed at:  /usr/lib/vmware
VMware version:  17.0.0.20800274
Patch Status: Patched (1)
SHA256: 59077ae6bb58aa85b9355fad6c9a0b0a8e2843815a3f518dab8daab71cf592b8
Patch Status: Patched (1)
SHA256: 1fa42ee705bd6920c48745569667f5d71e6a428de0ec245a6be3d0edddaa7435
Patch Status: Patched (1)
SHA256: 25f885e8406f0468176abde2fc3994404d8ee2414764a80dc4be2b91aab80295
Patch Status: Patched (1)
SHA256: c042c8dc7a26316ea71a840a1909732a8545c33d371ca665c70f8992994d9514


Press Enter key to continue...

```

###  vmware.log
[Please attach logs not copy them inline. It makes then issue unreadable and more work for me as I then have to copy it and attach as a file!]

[vmware.log](https://github.com/DrDonk/unlocker/files/10870580/vmware.log)

**Comment by DrDonk** [comment]
Please understand that AMD will not work currently and there is no unlocker fix available or possible. I am working on an OpenCore boot system to solve this.
